### ISSUE TITLE
Reservasjon mot digital kommunikasjon

### ISSUE THREAD

**Issue by anvike** [digipost/signature-api-client-dotnet#109]
Heisann,

I dokumentasjonen står det at "hvis signatar er reservert mot digital kommunikasjon vil oppdraget bli avvist og påfølgende uthenting av status for oppdraget vil gi en feil med informasjon om hvilke signatarer som er reservert." Kunne du ha gitt et eksempel på dette?

**Comment by SindreNordbo** [comment]
Hei,

XMLen som returneres av tjenesten i dette tilfellet ser ca sånn her ut:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<portal-signature-job-status-change-response xmlns="http://signering.posten.no/schema/v1">
    <signature-job-id>X</signature-job-id>
    <status>FAILED</status>
    <confirmation-url>https://api.signering.posten.no/api/123456789/portal/signature-jobs/X/complete</confirmation-url>
    <signatures>
        <signature>
            <status since="2017-09-20T12:21:43+02:00">RESERVED</status>
            <personal-identification-number>12345678910</personal-identification-number>
        </signature>
    </signatures>
</portal-signature-job-status-change-response>
```

I klientbiblioteket vil dere får en [`JobStatusChanged`](https://github.com/digipost/signature-api-client-dotnet/blob/dev/Digipost.Signature.Api.Client.Portal/JobStatusChanged.cs) med `Status` lik [`Failed`](https://github.com/digipost/signature-api-client-dotnet/blob/dev/Digipost.Signature.Api.Client.Portal/Enums/JobStatus.cs#L15). I tillegg vil det være minst én [`Signature`](https://github.com/digipost/signature-api-client-dotnet/blob/dev/Digipost.Signature.Api.Client.Portal/Signature.cs) med `SignatureStatus` lik [`Reserved`](https://github.com/digipost/signature-api-client-dotnet/blob/dev/Digipost.Signature.Api.Client.Portal/SignatureStatus.cs#L11).

Eventuelle andre mottakere som _ikke er reservert_ vil ha status `NOT_APPLICABLE`.

**Comment by asjafjell** [comment]
Jeg lukker denne, @anvike, og så kan du opprette et nytt issue om du skulle støte på noe annet.
