### ISSUE TITLE
Ingen public Constructor/konstruktør på Digipost.Signature.Api.Client.Portal.Signature v4.0.0.0

### ISSUE THREAD

**Issue by talisker77** [digipost/signature-api-client-dotnet#110]
Er det noen grunn til at Digipost.Signature.Api.Client.Portal.Signature ikke eksponerer en public constructor, mens  Digipost.Signature.Api.Client.Direct.Signature gjør?

Vi har laget noen Fake implementasjoner av både direct og portal (for testing internt) og opprettelse av Signature er ikke lenger mulig i versjon 4.0.0.0 
![image](https://user-images.githubusercontent.com/713604/30637451-a561d2e2-9df8-11e7-88eb-99f7f2735cc7.png)

Hvordan kan vi få laget en Signature hvis vi vil fake en Portal.Client når vi tester, hvis dere ikke vil eksponere en public constructor?

På forhånd takk.

**Comment by asjafjell** [comment]
Heisann, @talisker77! 

Dette er en glipp og blir fikset snarlig.

**Comment by talisker77** [comment]
Den er god.
