### ISSUE TITLE
Feiler nedlasting av pades når en henter 8 eller flere oppdrag samtidig

### ISSUE THREAD

**Issue by talisker77** [digipost/signature-api-client-dotnet#115]
![signering underlying connection closed](https://user-images.githubusercontent.com/713604/32722241-9152cc20-c869-11e7-9555-c7882a9e3b18.png)

Hvis en starter opp en portal klient i en flertrået applikasjon og har utestående 8 eller flere oppdrag samtidig opplever en at en får følgende feil:
{The underlying connection was closed: An unexpected error occurred on a send.} (se vedlagt bilde).

Klientbilbotek: 
<package id="api-client-shared" version="3.0.0" targetFramework="net461" />
<package id="digipost-signature-api-client" version="4.1.1" targetFramework="net461" />

Dette kan reproduseres hver gang en har sent flere enn 8 oppdrag. Stopper klienten. Signerer alle oppdrag i portalen.
Og starter klienten igjen. 
`
(await PortalClient.GetPades(new PadesReference(new Uri(message.PadesUrl)))).ReadFully();
`
Denne kodesnutten vil en da treffe 8 ganger samtidig, og da krasjer det.

Håper dere kan se på denne og gi en tilbakemelding.

**Comment by asjafjell** [comment]
Dette er finurlige greier, @talisker77. Vi skal ta en runde her internt på om det er begrensninger på vår side eller om det er noe rusk i klieneten. For ordens skyld, slik at vi har noe litt mer konkret, kunne dere lagt ved et kodeeksempel som står seg fint alene slik at vi kan teste det samme?

**Comment by asjafjell** [comment]
Da har jeg tatt en prat med @kagkarlsson, og om vi har forstått det riktig så vil du ved mer enn 10 samtidige connections opprettet innenfor de siste 3 sekundene bli stoppet. Om dere bruker en connection pool som overholder dette så bør det fungere. Så om dere holder oppe 2-3 connections i tillegg til de 8 som lages så vil det definitivt kunne bli noe krøll her.

**Comment by talisker77** [comment]
Det er nok dette som skjer, da vi oppretter 1-2 connections for poll mot asynkrone oppdrag (manuell og maskin til maskin). Deretter vil 8-9 connections bli opprettet når skal laste ned 8 eller flere oppdrag som er signert/avvist. Så ved oppstart der flere oppdrag er klar for nedhenting, så vil en måtte strupe samtidige tilkoplinger innenfor siste 3 sekunder. 
Gjelder de samme parameterne i produksjons-miljøet?

**Comment by asjafjell** [comment]
Dette er på tvers av alle miljøer, men det er ikke gjort store avveininger for disse tallene. Hva er behovet deres for å holde mer enn 8 connections åpne samtidig? Er det primært for å kunne laste ned mange store dokumenter på kort tid?

**Comment by talisker77** [comment]
Som beskrevet over, så skjer dette i hovedsak etter at en har hatt klient-tjenesten nede og i mellomtiden har det blitt signert oppdrag. Slik vi har løst dette, medfører dette at en får et stort volum av tilkoplinger på kort tid. Ser behovet for å lage mekanismer for å unngå DDoS, men hvis dette ikke er årsaken til dette, så kan en trygt ta opp antallet. Vi kan nok også se på mekanismer for ta ned antall samtidige tilkoplinger, slik at vi ikke komme opp i dette scenariet.

**Comment by asjafjell** [comment]
Vi har kommet fram til at 10 connections per avsender bør være tilstrekkelig, så løsningen for dere blir nok å holde på en connection pool. Jeg lukker denne for nå :)
