### ISSUE TITLE
Code for check status of signing document

### ISSUE THREAD

**Issue by sourabhmalani** [digipost/signature-api-client-dotnet#119]
Hello Team,

 http://digipost.github.io/signature-api-client-dotnet/v4.x/#get-portal-job-status-change

I am trying to implement code to check status of signing document using above links. I have specified the values for organization number and thumbprint,

**var clientConfiguration = new ClientConfiguration(Environment.DifiTest, certificateThumbprint, new Sender(organizationNumber));**

But on above line it is showing below error message.

**Could not load file or assembly 'Digipost.Api.Client.Shared, Version=3.0.0.0, Culture=neutral, PublicKeyToken=13a04c7692843c1c' or one of its dependencies. The system cannot find the file specified.**

I have installed the latest package of digipost-api-client but it is not contain any assembly or dll file named Digipost.Api.Client.Shared.

Please check this and let us know if we are missing anything to run the sample code.

Regards,
Sourabh Malani

**Comment by asjafjell** [comment]
Hi!

Can you please provide us with the version you are running of the _signature-api-client_?

Hope to hear from you soon.

**Comment by sourabhmalani** [comment]
Hello Team,

We are using signature-api-client version 4.1.1.0 for this.

Regards,
Sourabh Malani

**Comment by asjafjell** [comment]
There has not been reported any errors with this version, so I would recommend checking that you do not have any `BindingRedirect`s in the application's configuration file for api-client shared. If this does not fix it, let me know so we can check what is causing your issues next week.

**Comment by sourabhmalani** [comment]
Hello Team,

We have checked this there is bindingredirects in web.config.  I have attached the web-config.txt file for more information.

Please check this and let us know what modification do we need to require.

Regards,
Sourabh Malani

[web-config.txt](https://github.com/digipost/signature-api-client-dotnet/files/1486598/web-config.txt)

**Comment by asjafjell** [comment]
Hi, and sorry for the late reply.

I have now tested version 4.1.1 with creation of portal job and getting status. It worked flawlessly. There should be no binding redirects for this library, unless you have any other dependencies to api-client-shared in your project or some of the more general dependencies like Newtonsoft.Json. This can typically happen if you are integrating with digipost-api-client-dotnet at the same time. 

I am sorry to say that this is something you have to debug on your own, because this is not a problem with the library as far as I can see. Have you tried creating an empty project with just the code for the signature client, ad see if the problem still persists?

**Comment by sourabhmalani** [comment]
Hello Team,

Thank you for your reply.

http://digipost.github.io/signature-api-client-dotnet/v4.x/#get-portal-job-status-change

Again, I have tried to run the sample code for check status of signing document using above links. I have specified the values for organization number and thumbprint,

I am getting error at clientconfiguration. I have referenced the sample code of above url. I have attached screenshot of this.

I am running code in VS profession 2015 in .net framework 4.5.

Can you please provide working sample code for this.

Regards,
Sourabh Malani
![screenshot_1](https://user-images.githubusercontent.com/7112894/33133723-ab2b06c4-cfc3-11e7-81da-5966da1b0da9.jpg)

**Comment by asjafjell** [comment]
Hi! The client is .NET 4.6, so I am unsure how you managed to install it to a 4.5 solution. Please let me know if it works to upgrade your project.

**Comment by sourabhmalani** [comment]
Hello Team,

I have changed framework from .NET 4.5 to .NET 4.6. Now it is not showing error at clientconfiguration.

**Comment by asjafjell** [comment]
Great to hear that you have figured out how to run the library properly. 

When it comes to debugging, this is something you have to do for yourself. Unfortunately, we can not help you with every issue. I encourage you to read the error messages, they are very descriptive.
