### ISSUE TITLE
Får ikke signert oppdrag i difitest

### ISSUE THREAD

**Issue by talisker77** [digipost/signature-api-client-dotnet#122]
Feil i difitest:
![feil](https://user-images.githubusercontent.com/713604/34480236-7a3d2648-efab-11e7-8e77-b969571136f9.png)

Signerer med BankId og da feiler dette. Dette var ikke noe problem før vi skiftet sertifikat og vi var markert som privat. Vi tester nå med sertifikat avtrykk: 69 e2 9a e9 f6 d8 f6 55 29 72 76 c6 7c 95 4c 75 39 80 09 52. 
Hvis jeg velger gå videre når oppdraget feiler, forsvinner oppdraget. 

Har også et oppdrag i qadifi hvor jeg får samme feil. 

Ble oppfordret av support digipost å ta kontakt her. 

Takk for hjelp.

**Comment by asjafjell** [comment]
Jeg er usikker på om jeg skjønner helt hva som er problemet ditt her. Jeg prøver å bryte det opp litt.

**1. Bytte av sertifikat**: Får du til å lage et oppdrag med et nytt sertifikat uten feilmelding, så er sertifikatbyttet ok. Thumbprintet er ikke noe jeg kan bruke til å feilsøke med, det er knyttet til henting fra sertifikatlageret på Windows.

Var det slik at dere tidligere var registrert som en offentlig virksomhet?

**2. Hvis jeg velger gå videre når oppdraget feiler, forsvinner oppdraget.**
Jeg er litt usikker på hva mener med å gå videre når oppdraget feiler. Tenker du da på at du går til dokumentoversikten for innlogget signatar? Hvis det er feilet så vil det ikke lenger være i dokumentoversikten som et oppdrag klart for signering. 

Jeg anbefaler deg å teste med et annet dokument som du vet ikke er skrivebeskyttet eller passordbeskyttet, slik at vi får luket ut den feilkilden. Beskyttelse av dokument er ikke noe vi får innsikt i siden signeringen av dokumentet gjøres av Signicat.

**Comment by talisker77** [comment]
Var det slik at dere tidligere var registrert som en offentlig virksomhet?
- Vi har kontaktet support@digipost og fått byttet fra privat til offentlig, flere ganger. Dette har før vært problemfritt. Har kanskje ikke noe med saken å gjøre, men jeg ville nevne dette. 

2.
![image](https://user-images.githubusercontent.com/713604/34483395-79302094-efbe-11e7-9d22-54a4f6a4b639.png)
Eksempel på nr 2. Bildet vises etter at passordet for BankId er tastet inn. Her viser knappen går videre, og hvis jeg trykker på denne vil oppdraget ikke lenger være mulig å finne i portal, og en får heller ikke status endring fra portal når vi poller på endrete oppdrag. Dette gjelder både difitest og fra bilder difiqa. Signerer med BankId og bruker 15079413205 som test person. 

Dokumentet har vil benyttet utallige ganger for testing, så kan ikke se at dette skal være en årsak til problemet. 

Håper dette kan klare litt opp.

**Comment by asjafjell** [comment]
Takk for god info.

Vi gikk inn i Difiqa og fant oppdrag 1124. Vi testet å signere dette oppdraget nå og det gikk helt fint, så vi er usikre på hva problemet kan være. Kunne du sjekket at du ikke blokkerer tredjeparts-cookies, og eventuelt teste på en annen maskin og/eller nettleser?

**Comment by talisker77** [comment]
Jeg bruker Edge og der skjer det kosekvent. Logget inn i Chrome "inkognito" og tillot alle cookies, og da gikk dette helt greit. Dette har jeg vært obs på tidligere og har derfor ikke bruk Chrome, da jeg bruker å blokkere 3dje parts cookies. I Edge har jeg ikke hatt denne begrensningen og har derfor ikke hatt dette problemet før.
![image](https://user-images.githubusercontent.com/713604/34514047-a46fbbea-f06b-11e7-93e9-6ec3e6fd97a0.png)
Så dette problemet ser ut til å være relatert til Edge browser.

**Comment by asjafjell** [comment]
Fint å høre at du får det til å fungere da, men kjipt at det ikke fungerer i den nettleseren du ønsker.

Det er usikkert hvorfor dette har begynt å feile i Edge. Det er mulig det nylig er gjort noen endringer i Edge som gjør dette. Vi skal høre med Signicat om dette er et problem de er kjent med. Dette vil uansett bare være et problem i testmiljøet siden Iframe til Signicat kjører under et subdomene i produksjon. 

En hurtigfiks for deg vil være å lage et unntak i blokkeringen av cookies for akkurat dette tilfellet. Du hører fra oss om dette er noe vi kan gjøre noe med.

**Comment by talisker77** [comment]
Det går greit å bruke Chrome, men har ikke før hatt problemer med Edge, nettopp fordi jeg ikke hadde blokkert tredjepartskapsler. Siden disse cookiene kommer fra mange domener blir de gjerne klassifisert som tredjeparts og dermed blokkert hvis du har på denne innstillingen i en browser. 
Uansett greit å avklare at problemet ser ut til å være nettleser og miljø.
Takk for hjelp.
