### ISSUE TITLE
Spørsmål omkring ny løsning med køer

### ISSUE THREAD

**Issue by talisker77** [digipost/signature-api-client-dotnet#123]
Er det gitt et antall køer en organisasjon kan opprette eller kan en teoretisk har en kø pr. oppdrag? #

**Comment by asjafjell** [comment]
Det er ikke satt en begrensning på dette på nåværende tidspunkt, men om du fikk dokumentasjonen fra Difi så er det spesifisert at det er for å kunne skille mellom f.eks. forskjellige avdelinger i en organisasjon. Å lage 1 per melding vil altså fungere nå, men er misbruk av APIet og vil muligens ikke fungere på et senere tidspunkt.

**Comment by talisker77** [comment]
Takk for svar. 

Det gir selvfølgelig ingen verdi og opprette køer for hvert oppdrag, ville undersøke om det var begrensninger. Vi jobber ut i fra det scenariet at en organisasjon har flere tjeneste-leverandører som benytter seg av signering, slik at en kan skille mellom den enkelte leverandør sin installasjon av signering. Uten begrensning av antall køer kan en også granulere på andre egenskaper også, så sant dette ikke blir oppfattet som misbruk av API'et.

**Comment by asjafjell** [comment]
Ikke noe problem! Hovedpoenget her er altså at så lenge man har et bevisst og fornuftig forhold til hvordan køer fungerer så vil det ikke oppstå noen problemer.
