### ISSUE TITLE
Signeringsoppdrag for offentlig autentisert nivå tre feiler i signeringsprosessen i difitest

### ISSUE THREAD

**Issue by talisker77** [digipost/signature-api-client-dotnet#125]
Hei, 

Tester på sette IdentifierInSignedDocuments.Name på signeringsoppdraget for offentlig virksomhet.
Oppdraget er satt med nivå tre og autentisert , sikkerhetsnivå og signaturtype.
Har tidligere vært i kontakt med support@digipost og fått svar at dette skyldes at Folkeregister for testpersonen ikke har data. Er dette tilfellet, eller er det noe annet som forårsaker dette?

Vedlagt viser oppdrag url og feil.
![image](https://user-images.githubusercontent.com/713604/34611819-5bd2029a-f227-11e7-9e9b-fca1e76746d2.png)

Håper dere kan gi et avklarende svar.

Takker.

**Comment by SindreNordbo** [comment]
Hei,

Det stemmer at dette er årsaken til at du ikke får signert med denne brukeren. Når du poller på statuser vil du få tilbake en respons som indikerer at signaturen ikke kunne innhentes med status `SIGNERS_NAME_NOT_AVAILABLE`.

Hvis dere ikke har noen andre testbrukere, vil jeg anbefale å ta kontakt med DIFI som kan være behjelpelig med å skaffe dere brukere til ID-porten.

**Comment by talisker77** [comment]
Ok, takk for det. Kan ikke se at de er kommet tilbake med denne status. Er den hentet ned?
Dette vil vel ikke bli et problem i prod?

**Comment by SindreNordbo** [comment]
Statusen er hentet ned, ja.

Noen personer er nok også i denne tilstanden i prod, men jeg kjenner ikke datagrunnlaget til folkeregistrert godt nok til å vite omfanget. Jeg tipper det er svært få norske innbyggere hvis navn ikke er tilgjengelig i folkeregisteret.

**Comment by Ramung** [comment]
@talisker77 
Så godt som ingen vil være i denne tilstanden i produksjon. Det er fordi regimet som regulerer utstedelse av kvalifiserte person-sertifikat krever at man må være folkeregistrert for å få utstedt slike sertifikat (dette gjelder altså for sikkerhetsnivå 4) og fordi det kreves utsending av PIN-koder til folkeregistrert adresse ifm utstedelse av MinID (sikkerhetsnivå 3). 
Samlet sett betyr dette at alle som innehar eID som kan brukes til signering i tjenesten i utgangspunktet skal være folkeregistrert, og da vil tjenesten klare å hente navnet deres (med mindre man opplever nedetid).

**Comment by talisker77** [comment]
@Ramung Takk for avklarende informasjon.
