### ISSUE TITLE
Unable to create SSL/TLS secure channel

### ISSUE THREAD

**Issue by hardikCIS** [digipost/signature-api-client-dotnet#129]
When using the digipost signature API, facing issue in portalClient.GetStatusChange(); method related with "The request was aborted: Could not create SSL/TLS secure channel." please help for solution.

![image](https://user-images.githubusercontent.com/36002383/36298658-3019d132-131f-11e8-9796-8912e648b1b4.png)

**Comment by SindreNordbo** [comment]
Hello.
Seems like you are having trouble establishing a secure connection over TLS, so you should probably verify that your certificate is installed correctly and is a valid certificate for the service.
We have described how to install certificates [in the documentation](http://digipost.github.io/signature-api-client-dotnet/v4.x/#install-business-certificate-in-certificate-store) and also have [some requirements for certificates and troubleshooting tips](https://github.com/digipost/signature-api-specification/blob/master/integrasjon/sikkerhet.md#to-veis-tls). The last link is only in Norwegian, but you might use Google Translate or a similar service to translate it to your preferred language.
