### ISSUE TITLE
Hvordan telles åpne connections?

### ISSUE THREAD

**Issue by anvike** [digipost/signature-api-client-dotnet#131]
Hei,

Ref. "Feiler nedlasting av pades når en henter 8 eller flere oppdrag samtidig #115"

Hvordan teller dere samtidige koblinger? Er det IP-adressen som definerer avsenderen?
Vi har noen potensielle caser hvor flere uavhengige avsendere er plassert på samme server.

**Comment by SindreNordbo** [comment]
Hei,

Informasjonen i #115 er nok litt utdatert. Vi tillater en del flere enn 10 samtidige connections, men har definert et tak.

Samtidige koblinger telles på IP-adresse, men hvis dere gjenbruker connections tror jeg ikke dere burde støte på problemer så lenge dere integrerer på en «fornuftig» måte, og ikke hamrer oss med requests for å laste ned veldig mange store filer i parallell for eksempel.

Hvor mange uavhengige avsendere er det snakk om?

**Comment by anvike** [comment]
Hei igjen,

Det er snakk om 7 forskjellige avsendere. Det skjer sporadisk, som trolig vil si at dette skjer når 1 eller flere avsendere får treff samtidig på uavhentede oppdrag.
Har dere logger som kan bekrefte/avkrefte om man når dette taket?

**Comment by SindreNordbo** [comment]
Gjenbruker dere connections? Hvor ofte poller dere APIet?

I følge [integrasjonsguiden](https://github.com/digipost/signature-api-specification/blob/master/integrasjon/asynkron.md#hvor-ofte-skal-du-polle) skal dere bruke tidspunktet som returneres fra tjenesten for å schedulere neste polling, dette er per i dag konfigurert opp til å være hvert 10. minutt (men kan endres, så ikke hardkod dette i applikasjonen deres).
Hvis dere poller oftere enn dette får dere en statuskode som indikerer at dere må vente litt og vil uansett ikke motta statusendringer før tidspunktet har passert. Hvis dere derimot bruker dette tidspunktet bør det være "ganske" usannsynlig at flere avsendere har uavhentede oppdrag samtidig.

**Comment by asjafjell** [comment]
Etter lengre tids inaktivitet så lukker jeg denne.
