### ISSUE TITLE
Hvordan kansellerer man et signeringsoppdrag?

### ISSUE THREAD

**Issue by OleJorgenHansen** [digipost/signature-api-client-dotnet#132]
Hvis en saksbehandler ved en feil sender ut en signering så vil man kansellere den.
DIFI har sagt at dette er mulig ved å sende et kall til en CancellationUrl.
Jeg klarer ikke å finne noe om dette i dokumentasjonen.

Kan noen forklare hvordan dette gjøres.
Vi bruker Portal varianten av tjenestene.

**Comment by Ramung** [comment]
Hei @OleJorgenHansen 
Hvis dere bruker portal, skal dere ikke sende kall til noen cancellationUrl, men finne signeringsjobben i fileteret "Venter" i portal og velge "Kanseller signering". Dere bes da om en bekreftelse (pop-up). Gjenta "Kanseller", og jobben er kansellert. Saksbehandler mottar bekreftelse til angitt kontaktinformasjon. Kansellerte signeringsjobber legger seg i filteret "Stoppet".

**Comment by OleJorgenHansen** [comment]
Har du et kodeeksempel som beskriver hvordan dette gjøres?

Jeg skjønner ikke hva som menes med filteret "Venter" og "Stopper". Er det starusen på jobben du mener?
Jeg finner ingen metoder som kan se ut til å gjøre "Kanseller signering" jobben.

**Comment by Ramung** [comment]
Beklager, @OleJorgenHansen, her har jeg nok lest litt fort. Dere bruker 'portal-jobs', og det er jo noe ganske annet enn tjenestens portalgrensesnitt for avsendere. 

Prøver igjen: I portal-signature-job-response mottar dere en cancellation-url, slik du skriver. Det er denne man bruker for å trekke tilbake oppdraget. Dokumentasjon finnes på [https://github.com/digipost/signature-api-specification/blob/master/schema/xsd/portal.xsd](url)

**Comment by asjafjell** [comment]
Vi ser vi mangler dokumentasjon på kansellering på klientbiblioteket. Vi har ikke noe kodeeksempel, men  det er metoden `PortalClient.Cancel` som skal anvendes for formålet. Se gjerne i [kildekoden](https://github.com/digipost/signature-api-client-dotnet/blob/dev/Digipost.Signature.Api.Client.Portal/PortalClient.cs#L135) for litt mer informasjon. Et utdypende eksempel vil komme på et senere tidspunkt.

**Comment by OleJorgenHansen** [comment]
Jeg fant ut av det.

Etter sending tar man vare CancellationReference og lagrer det i databasen:
            var client = new PortalClient(clientConfiguration);
            ...
            JobResponse portalJobResponse = await client.Create(portalJob);
            String jobId = portalJobResponse.JobId.ToString();
            String signeringCancelUrl = portalJobResponse.CancellationReference.Url.AbsoluteUri;
			
			
Hvis sender velger å avbryte så brukes man denne lagrede verdien for å avbryte:			
			var client = new PortalClient(clientConfiguration);
			...
			await client.Cancel(new CancellationReference(new Uri(signeringCancelUrl)));

Url'en er på formen (mot test systemet):
https://api.difitest.signering.posten.no/api/<orgnr>/portal/signature-jobs/<jobId>/cancel

**Comment by asjafjell** [comment]
Jeg har nå lagt til et eksempel for kansellering av signeringsoppdrag. Vennligst se [dokumentasjonen](http://digipost.github.io/signature-api-client-dotnet/v4.x/#cancel-portal-job) for mer info.
