### ISSUE TITLE
avhengighet til Newtonsoft.Json <11.0.0

### ISSUE THREAD

**Issue by talisker77** [digipost/signature-api-client-dotnet#135]
digipost-signature-api-client er avhengig av Newtonsoft.Json lavere enn versjon 11. 
Newtonsoft.Json er nå i versjon 11.0.2.
Oppdatering av Newtonsoft.Json feiler på grunn av denne avhengigheten. 
i *.nuspec filen er det satt maks versjon:

    <dependency id="Newtonsoft.Json" version="[6.0.4,11)" />

Hvis denne endres til vil ikke nyere versjoner hindre oppdatering:

    <dependency id="Newtonsoft.Json" version="(6.0.4,)" />

Kan dette oppgraderes. Vil ikke tror signature-api-client-dotnet er versjonsavhenging av Newtonsoft.Json .

**Comment by asjafjell** [comment]
Kan dere teste versjon [4.2.0.198-beta](https://www.nuget.org/packages/digipost-signature-api-client/4.2.0.198-beta) og rapportere om det fungerer?

**Comment by talisker77** [comment]
Oppdatert pakke digipost-signature-api-client
til: <package id="digipost-signature-api-client" version="4.2.0.198-beta" targetFramework="net461" />
Fjerning av avhengighet til Newtonsoft.Json ser ikke ut til å ha påvirkning på løsning.
