### ISSUE TITLE
Portal: Finne utsendt Reference på en JobStatusChange/JobID

### ISSUE THREAD

**Issue by amuaa** [digipost/signature-api-client-dotnet#137]
Hei,

Lurte på om det finnes en måte å få tak i referansen (Reference) for en Job i det man poller og registrerer at det skjer en endring i en portal-case.

Det er "nice-to-have" for oss da det forenkler arkiveringsprosessen av pades i etterkant. Rent konkret slipper vi da å lagre informasjon om hvilken referanse som har hvilket JobID, noe vi må gjøre på en litt uelegant måte pga begrensninger i programvaren vi integrerer mot.

Mvh,
Amund/Canon

**Comment by asjafjell** [comment]
Heisann, Amund!

Jeg kan ikke svare på hvorfor vi ikke leverer ut avsenders referanse på statusoppdateringene. Dette er noe vi bare skal få fikset så snart som mulig. Jeg kan ikke love noe tidspunkt akkurat nå ettersom det er sommerferie. Du hører fra oss på dette issuet når det er fikset.

**Comment by SindreNordbo** [comment]
Hei igjen, @amuaa .

Vi har publisert en ny versjon ([4.3.0](https://www.nuget.org/packages/digipost-signature-api-client/4.3.0)) som inkluderer denne referansen [i status-endringen](https://github.com/digipost/signature-api-client-dotnet/blob/v4.3.0/Digipost.Signature.Api.Client.Portal/JobStatusChanged.cs#L25). Håper det gjør det lettere for dere å bruke tjenesten vår :)

Vh,
Sindre
