### ISSUE TITLE
Får UNEXPECTED_SERVER_ERROR når en skal hente pades

### ISSUE THREAD

**Issue by talisker77** [digipost/signature-api-client-dotnet#140]
![image](https://user-images.githubusercontent.com/713604/43443908-9be08dfc-94a2-11e8-938e-ffae2deaa3d3.png)

Når jeg kaller denne addressen får jeg UNEXPECED_SERVER_ERROR:
"https://api.difitest.signering.posten.no/api/968041819/portal/signature-jobs/11957/pades"

Oppdraget er ferdig og signert, jeg får ned XADES. Kan noen hjelpe meg å forstå hvorfor dette skjer?
Miljøet er som følger:
![sign env](https://user-images.githubusercontent.com/713604/43444013-f42d7556-94a2-11e8-8f24-17a6a3d1c6e9.png)

Håper dere kan hjelpe med å belyse problemet. Vi har sett lignende situasjoner i produksjon, men det er ikke nødvendig at det er sammenheng her. 

Problemet er uansett konsekvent. Bruker 4.3.0 av dot net signeringsklienten.

**Comment by SindreNordbo** [comment]
Hei.

Beklager sent svar. På grunn av ferieavvikling har denne dessverre gått oss hus forbi.
Feilene du opplevde var forårsaket av en forbigående feil med PAdES-nedlasting på formiddagen 31. juli. Dersom dere prøver igjen nå vil nedlasting fungere.
