### ISSUE TITLE
order ikke med i xml bundle for portal sign

### ISSUE THREAD

**Issue by talisker77** [digipost/signature-api-client-dotnet#141]
Sendte oppdrag med 2 signatarer og satt Order til henholdsvis 1 og 2. I portal fikk begge signatarer oppdraget tilgjengelig med en gang. 
Xml fra bundle: 
```xml
<?xml version="1.0" encoding="utf-8"?>
<portal-signature-job-manifest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://signering.posten.no/schema/v1">
  <signers>
    <signer>
      <personal-identification-number>15079413205</personal-identification-number>
      <signature-type>ADVANCED_ELECTRONIC_SIGNATURE</signature-type>
      <notifications-using-lookup>
        <email/>
      </notifications-using-lookup>
      <on-behalf-of>SELF</on-behalf-of>
    </signer>
    <signer>
      <personal-identification-number>01040800138</personal-identification-number>
      <signature-type>ADVANCED_ELECTRONIC_SIGNATURE</signature-type>
      <notifications-using-lookup>
        <email/>
      </notifications-using-lookup>
      <on-behalf-of>SELF</on-behalf-of>
    </signer>
  </signers>
  <sender>
    <organization-number>968041819</organization-number>
  </sender>
  <document href="2018080933060document" mime="application/pdf">
    <title>Signert DOKUMENT FOR SIGNERING</title>
    <description>DOKUMENT FOR SIGNERING</description>
  </document>
  <required-authentication>4</required-authentication>
  <availability>
    <activation-time>2018-08-09T00:00:00+02:00</activation-time>
    <available-seconds>291144</available-seconds>
  </availability>
  <identifier-in-signed-documents>PERSONAL_IDENTIFICATION_NUMBER_AND_NAME</identifier-in-signed-documents>
</portal-signature-job-manifest>
```
Jeg mener at order skulle vært med her, men den ser ut til ikke å komme med. 
Bruker følgende pakker:
```xml
<package id="api-client-shared" version="3.0.0" targetFramework="net461" />
<package id="digipost-signature-api-client" version="4.3.0" targetFramework="net461" />
```

**Comment by asjafjell** [comment]
Heihei! Dette må vi få tatt en kikk på. Vi sjekker det opp så snart vi har mulighet, og så hører du fra oss.

**Comment by anvike** [comment]
Heisann,

Har dere en oppdatering på denne?

**Comment by anvike** [comment]
Supert! Takk for tilbakemelding :)

**Comment by asjafjell** [comment]
Den her har dessverre stått helt brakk, selv om det er en relativt liten greie. Kunne du gitt oss en pekepinn på hvor viktig den er å få løst den, slik at vi kan prioritere den opp mot andre oppgaver. Beklager på det sterkeste.

**Comment by anvike** [comment]
Det er en del som benytter integrasjonen som har etterlyst spesielt denne funksjonaliteten. Uten denne er det veldig begrenset hvilke type dokumenter som kan sendes til signering.

Om vi kunne ha fått en avklaring i løpet av neste uke hadde det hjulpet oss masse. Vi vil stå klar til å  implementere og teste nytt løsningsforslag omgående.

**Comment by SindreNordbo** [comment]
Hei. Vi har omsider lansert en beta-versjon `4.3.0.217-beta` som inneholder en fiks på dette. Gi gjerne en tilbakemelding på om det løser problemet for dere :) Den blir nok tilgjengelig på Nuget i løpet av kort tid.

I samme slengen har vi fjernet strong name signing. Hvis dere trenger å ha biblioteket i global assembly cache må dere dermed signere det selv. Hvis ikke bør det være helt uproblematisk å oppgradere til beta-versjonen.

@anvike @talisker77

**Comment by talisker77** [comment]
Hei.
Da har jeg testet, og det virker tilsynelatende. Men bundle som blir laget or ikke `order`-attr i manifest.xml når den blir logget.  Er dette bare noe som er glemt å legges til i farten?

**Comment by talisker77** [comment]
Ok, dette virker som forventet nå.
