### ISSUE TITLE
DirectClient eller PortalClient

### ISSUE THREAD

**Issue by trond-eirik** [digipost/signature-api-client-dotnet#154]
Hei
Vi har signeringsoppdrag hvor flere personer (7 stk) skal signere ett dokument.
Noen av disse er ansatte, andre er privatpersoner.
Vi ønsker en løsning hvor de ansatte kan sitte og arbeide mest mulig i sine egne fagsystemer, mens privatpersonene skal gå via vår portal. Det er i praksis kun signeringssermonien vi ønsker å bruke. Vi vil sannsynligvis ønske mer kontroll med informasjonen som går ut til brukerne enn det det virker som om vi får dersom vi bruker varslingsmekanismen i signaturtjenesten.
For de ansatte vil vi ikke ønske varsling i det hele tatt - de vil få opp denne informasjonen i oversikter i egen fagapplikasjon.

Normalt vil signeringen utføres samme dag som oppdraget legges ut, men det vil også kunne gå flere dager før alle har signert. En av brukerne skal signere etter alle de andre brukerne.

Gitt dette behovet, vil dere foreslå at vi bruker DirectClient eller PortalClient?
Er det spesielle forskjeller mellom dem vi bør være oppmerksomme på?

**Comment by asjafjell** [comment]
Heisann! 

Vi har en del dokumentasjon på dette, men vi skjønner at den kan være både overveldende og uoversiktlig. Vi kommer snart til å gjøre om på dette, men foreløbig kan jeg jo peke deg litt i riktig retning.

Du ønsker å la ansatte jobbe i sine _egne fagsystemer_ og la privatpersoner gå via _deres portal_. Jeg vet ikke noe om hvilken virksomhet du jobber for eller hvordan disse systemene jobber sammen, men helt kort kan jeg oppsummere -`DirectClient` vil nok gi det dere ønsker:
- Oppdrag lages via APIet vårt. Dette vil slik jeg forstå, gjøres av deres fagsystem. Fagsystemet lager en jobb med `DirectClient` og dere får tilbake lenker som dere sender brukere videre til.
- Lenken serveres av deres portal. Dere har da mulighet til å komme med en side med den informasjonen dere ønsker på deres side og så sender dere bruker videre via lenken lagd av fagsystemet når dere måtte ønske. 
- Brukeren av fagsystemet blir sendt tilbake til en URL bestemt av dere for de tre casene: `Failed`, `Canceled` og `Completed`. 
- Så lenge det er API som brukes for å opprette oppdrag så er det ingen som vil få noen varsler i deres fagsystem fra oss. Om dere ønsker å lage varsler ut fra hendelser under signering så er det helt opp til dere.

Alt dette er forklart overordnet i [api-spesifikasjonen](https://github.com/digipost/signature-api-specification) og i dybden i den [funksjonelle dokumentasjonen](http://digipost.github.io/signature-api-specification/v1.0/)

**Comment by trond-eirik** [comment]
Takk, høres ut som om dette er den mest aktuelle løsningen for oss.
Jeg var i tvil pga at oppførselen vår er asynkron, ikke synkron. DirectClient eksemplene henviser ofte til synkron oppførsel og mange eksemplerer omhandler dette. Det virker som om det har vært en utvikling og bevisstgjøring og jeg ser at det nå virker å være mer direkte-integrasjon vs portal-integrasjon.

Har tre små oppfølgingsspørsmål:
1) hvordan kan vi kansellere ett oppdrag etablert med DirectClient?
2) I oppdrag etablert med både DirectClient og PortlClient er det en initiell side hvor man får presentert infomelding og link for å åpne dokumentet. I PortalClient får brukeren informasjon om antall signatarer totalt og antall som har signert. I DirectClient får man ikke denne informasjonen. Det burde vel vært avhengig av antall signerere, ikke Direct eller Portal
3) ved bruk av DirectClient er det ofte ikke behov for mellomsiden, denne informasjonen vil brukeren typisk få fra vår løsning. Er det mulig å legge inn en opsjon som gjør at man kan hoppe over denne siden og gå direkte inn på siden for å se og signere dokumentet?

**Comment by asjafjell** [comment]
Vi har kluss med navngiving på tvers av forskjellige deler av dokumentasjonen, så jeg skjønner at du er forvirret. Vit at vi jobber med å få dette synkronisert (pun not intended).

1. Kansellering her er [ikke nødvendig](http://digipost.github.io/signature-api-specification/v1.0/#kansellere-signeringsoppdrag). Dere sørger selv for varsling og hvordan sluttbruker skal forholde seg til oppdraget. Et synkront oppdrag vil leve [maksimalt 30 dager](http://digipost.github.io/signature-api-specification/v1.0/#opprette-signeringsoppdrag) for å sikre at det ikke blir signert for lenge etter opprettelse. For å kansellere trenger du altså bare å slutte å bruke det i deres systemer.
2. Beklager, men denne informasjonen er ikke tilgjengelig på den siden. 
3. Hvis du unnlater å sende med beskrivelse [Document.Message](https://github.com/digipost/signature-api-client-dotnet/blob/master/Digipost.Signature.Api.Client.Direct/Document.cs#L7), så vil vi sende undertegner rett videre til neste steg i signeringsflyten.

**Comment by trond-eirik** [comment]
OK, takk
