### ISSUE TITLE
Contact information by lookup is required

### ISSUE THREAD

**Issue by trond-eirik** [digipost/signature-api-client-dotnet#155]
Bruker PortalClient i .Net biblioteket og ønsker at signatarene skal varsles på en annen e-post og sms-adresse enn det som ligger i kontakt- og reservasjonsregisteret.
Initierer signatarene (det er to på dennejobben) slik som dette:
var signer = new Signer(
                    new PersonalIdentificationNumber("123456789"), 
                    new Notifications(
                        new Email("epost@post.no),
                        new Sms("12345678")
                    )
                );

Dersom jeg forsøker å opprette oppdrag på samme fødselsnr og med alternativ varslingsadresse i portalen så går det bra. 
Men når jeg forsøker å opprette oppdraget via kode får jeg denne feilen:
UnexpectedResponseException: ErrorType:CLIENT, ErrorCode: CONTACT_INFORMATION_BY_LOOKUP_IS_REQUIRED, ErrorMessage: Providing contact information is not permitted. Contact information must be retrieved by lookup.

Jeg antar at det er noe jeg overser eller ikke forstår her, men det hadde vært fint med en forklaring på hva som må gjøres for å kunne angi alternativ varslingsadresse også gjennom API'et.

PS: NB: Jeg har sett på metoden der man registrerer kontaktinformasjon slik det er gjort i eksemplene, ref:
new Signer(new ContactInformation  { Email = new Email("email3@example.com"), Sms = new Sms("77777777") })
Men når man gjør det slik som dette har jo ikke signereren hverken fødselsnr eller navn. Dermed er det jo ikke noe som forteller hvem signerer er. Jeg ville tro det da var en annen måte å registrere fødselsnr på, men jeg har ikke funnet den. Hvordan er dette tenkt å virke?

**Comment by asjafjell** [comment]
Av informasjonen jeg får her forstår jeg det slik at du representerer en offentlig virksomhet. Feilmeldingen du får er at du ikke kan oppgi kontaktinformasjon fordi dette må gjøres ved oppslag. Du må da sende inn [ContactInformationUsingLookup](http://digipost.github.io/signature-api-client-dotnet/v5.x/#create-and-send-portal-signature-job). Du har med andre ord ikke lov til å bruke annen varslingsinformasjon enn den gitt av `Kontakt- og reservasjonsregisteret`

**Comment by trond-eirik** [comment]
Hei
Du har rett i at det er en offentlig virksomhet.
Men dersom personen det gjelder er i ett ansettelsesforhold eller utøvrrven rolle er det lov å oppgi annen kontaktinformasjon. Dette er ett valg i portal-brukergrensesnittet så det virker helt klart at dette er noe som skal være mulig å gjøre.
Kan det være at .net biblioteket for PortalClient mangler funksjonalitet som finnes når man bruker manuell integrasjon gjennom portalen?

**Comment by asjafjell** [comment]
Det virker som du har god oversikt og gir oss et godt utgangspunkt for å hjelpe dere. Vi er snart i gang med å oppdatere dokumentasjonen og innspillene her er et fint utgangspunkt for å se hva som er vanskelig. 

Det stemmer at det er mulig å omgå denne funksjonaliteten. Det gjør du ved å sette `OnBehalfOf=Other` på [Signer](https://github.com/digipost/signature-api-client-dotnet/blob/master/Digipost.Signature.Api.Client.Core/AbstractSigner.cs#L17).

**Comment by trond-eirik** [comment]
OK, takk, det tror jeg ikke jeg hadde klart å finne ut av alene!
