### ISSUE TITLE
Missing HTTP header

### ISSUE THREAD

**Issue by sveinblad** [digipost/signature-api-client-dotnet#156]
I've complied to the 'next permitted polling time', but when issuing a 'GetStatusChange' request in a 'permitted time slot', the production environment replies with HTTP status code **429**, but there is no HTTP header '**X-Next-permitted-poll-time**' present.

The client expects this header so that it can throw the '**TooEagerPollingException**'.

Source code from PortalClient.cs (version 5.0.2):

```
                case (HttpStatusCode) TooManyRequestsStatusCode:
                    var nextPermittedPollTime = requestResult.Headers.GetValues(NextPermittedPollTimeHeader).FirstOrDefault();
                    var tooEagerPollingException = new TooEagerPollingException(nextPermittedPollTime);
```

**Comment by asjafjell** [comment]
You will only get the `TooEagerPollingException` when you are too eager on polling. Otherwise, it will be a receipt. Please post the full flow on how you do polling, so that we can assist you on what is causing this. Also, please provide us with what you actually get as a response when you are excpecting `TooEagerPollingException`

**Comment by asjafjell** [comment]
When you are blocked, you will not get a next permitted poll time as you are blocked way before hitting the app. This is functionality that we have implemented purely as a result of the overly aggressive retry mechanism that you have, combined with the fact that we are presumably in the same Evry server hall, giving a response time of 0 to 1 millisecond. As soon as you back off for the time indicated, it should work as expected. Are you sure there is no other app doing calls on the API endpoint at the same time as you are testing? This will surely affect the result.

**Comment by sveinblad** [comment]
At the moment we have 2 different servers, each with different applications, hitting your environment. It might be that the second server is not complying to the retry scheme.

You should at least consider a graceful handling (custom exception) of this situation in your client. This might help others in the future to understand the 'problem'.

I'll close this issue for now.

Cheers
