### ISSUE TITLE
Returadresser ved synkron integrasjon

### ISSUE THREAD

**Issue by trond-eirik** [digipost/signature-api-client-dotnet#164]
Hei

Ut fra hva jeg ser så blir retur-adresser (ExitUrls) angitt pr. jobb når man bruker DirectClient (.net biblioteket).
Jeg tenker at dette vil fungerer mindre bra når man har forskjellige klienter.
Eksempelvis vil våre ansatte bruke en applikasjon, mens eksterne brukere vil bruke en annen.

Kunne løsningen vært utvidet slik at man kunne oppgi flere redirect-uri når man opprettet oppdraget, også kunne man velge hvilket sett man skulle bruke når man sendte brukeren til signeringssermonien?

Slik det er nå frykter jeg for at vi må gjøre mye ekstra arbeid for å få til å integrere løsningene våre skikkelig.

**Comment by asjafjell** [comment]
Nå forstår jeg bedre hvor du vil. Formuleringen var lettfattelig og fin. Det er uheldig av meg at jeg ikke forstod at det var det du mente. 

Slik løsningen vår er i dag så er det en sterk knytning mellom en signaturjobb og de tre Urlene. Dette er dessverre ikke noe vi kan gjøre noe med i en håndvending, men vi skjønner absolutt behovet deres. Jeg noterer det som et ønske, men akkurat nå kommer vi nok ikke til å endre dette før flere melder et lignende behov.

**Comment by trond-eirik** [comment]
Jeg tror vår løsning for dette må bli at vi returnerer brukeren til et sentralt punkt, også må vi finne ut hvilken type bruker det er og deretter gjøre en ny redirect i forhold til hva som er rett sluttpunkt.
Men det kompliserer nok løsningen ganske mye - så det kan gjerne bli løst dersom flere har dette behovet.
