### ISSUE TITLE
Muligheter for inject at HttpClientHandler i MutualTlsHandler/BaseClient.cs

### ISSUE THREAD

**Issue by talisker77** [digipost/signature-api-client-dotnet#170]
Vi har miljøer signeringstjenesten er plasser bak en proxy ,  hvor vi er avhengig av at http klienten i (Portal/Direct)Client må authentisere seg mot en proxy.
I BaseClient lager dere en HttpClientHandler uten muligheter for å håndtere evt. proxy hvor dotnet klienten er installert. 

Kunne  det blitt lagt opp til å kunne eventuelt overstyre HttpClientHandler som lages?
Evt lage en måte å kunne aktivere håndtering av Proxy.
```cs
 var proxy =  var cred = new NetworkCredential(username, password);
 var proxy = new WebProxy(url)
 {
      UseDefaultCredentials = false
 };
proxy.Credentials = cred;
var handler = new HttpClientHandler
{
    Proxy = proxy,
    PreAuthenticate = true,
    UseDefaultCredentials = false,
};
```

**Comment by asjafjell** [comment]
Heisann! Vi har ikke lagt til proxyhåndtering i klienten fordi behovet ikke har meldt seg enda. Dette er noe som absolutt er fint å ha. Du må gjerne lage en PR på det om du behvøver det veldig raskt.

**Comment by asjafjell** [comment]
Er dette fortsatt et behov dere har?

**Comment by talisker77** [comment]
Ja, behovet er det fortsatt. Så ville satt stor pris på om dette ble implementert.

**Comment by manuelAlonsoPerez** [comment]
Hei @talisker77 vi har released siste beta med proxy støtte i klient konfigurasjon, du kan gjerne teste den
