### ISSUE TITLE
Direkte integrasjon feiler når brukeren bruker forskjellige nettlesere

### ISSUE THREAD

**Issue by trond-eirik** [digipost/signature-api-client-dotnet#179]
Hei

Opplever følgende oppførsel når jeg tester løsningen:
1) Oppretter ett oppdrag
2) Følger linken jeg får tilbake i nettleseren og får opp dokumentet og mulighet til å signere
3) Åpner en annen nettleser (på samme enhet eller en annen enhet) og følger den sammen linken. Jeg får nå "Beklager, en feil har oppstått" Kunne ikke laste dokument. 
Jeg vil anta at dere også får det om dere forsøker å åpne opp dette signeringsoppdraget: 
https://difitest.signering.posten.no/signere/#/-/5urDy5ykdUgh-iZtoEJdMfeSOI-o_naL-zkPeBei8g4

Dette simulerer en bruker som først forsøker å åpne et dokument for å signere det i en nettleser men så finner ut at han må ta det senere eller ønsker å lese dokumentet på en større skjerm, og derfor bytter enhet etter å ha forsøkt med en enhet første gang.

Er dette en feil eller er det en hemmelig "sikkerhetsfeature"?
Jeg er litt usikker på hvor stort dette problemet vil være i praksis - men jeg ser helt klart for meg at bruksmønsteret burde kunne skje også under praktisk bruk.
Er dere kjent med problemstillingen?

**Comment by asjafjell** [comment]
Heisann! 

Dette er en sikkerhetsmekanisme for å sikre at det er den brukeren som var innlogget i deres tjeneste også er den som signerer dokumentet. Når den lenken er åpnet én gang så markeres den som brukt. Å kopiere lenken til en ny enhet vil derfor være en sikkerhetsrisiko og er ikke mulig. Dere må på deres side må håndtere en slik brukeroppførsel.

**Comment by trond-eirik** [comment]
OK, det at en lenke kun kan brukes en gang høres bra ut.

Men det betyr at vi har behov for å kunne gi brukeren en ny lenke.
Det er ikke helt opplagt for meg hvilket kall vi skal bruke (med DirectClient) for å få ut en ny signaturlenke.
Kan være at det bare er jeg som overser noe jeg burde se - men et lite hint hadde vært fint her.

**Comment by asjafjell** [comment]
Dere må da lage et nytt signeringsoppdrag :)
