### ISSUE TITLE
 Feil ved konvertering av kode fra C# til VB.NET  

### ISSUE THREAD

**Issue by andersmpaulsen** [digipost/signature-api-client-dotnet#180]
[Feilmeldinger (1).pdf](https://github.com/digipost/signature-api-client-dotnet/files/2866237/Feilmeldinger.1.pdf)

Håper noen som kan hjelpe

**Comment by asjafjell** [comment]
Heisann! Vi har ikke noen erfaring med Visual Basic. Hva har du funnet ut av til nå?

**Comment by asjafjell** [comment]
Siden vi ikke har hørt noe her på 2 uker så lukker vi denne. Så kan du lage en ny issue om du ønsker det.
