### ISSUE TITLE
UnexpectedResponseException: ErrorType: Server

### ISSUE THREAD

**Issue by talisker77** [digipost/signature-api-client-dotnet#187]
Hei, 

Vi opplever å få feil når vi spør på om endrede oppdrag:
```cs
var response = await PortalClient.GetStatusChange(
                            new Sender(
                                    OrgNr,
                                    new PollingQueue(null)
                                )
                        );
```
Vi byttet for en liten tid tilbake til et angitt kønavn, og vi mangler da oppdrag pollingqueue=null. 

Siden vi benytter oss både av direkte og portal oppdrag, så få vi ofte tooeagerpolling ved bruk av PollingQueueName=null og det var derfor vi satt inn et kønavn.

Kan dere se på dette snarest, evt ta kontakt for å diskutere mulige løsninger?

Takk.

Fra logg:
2019-03-12 09:49:43.132 +01:00 [Debug] Henter status for Tenant: "Gjøvik"(Id:1), org: "940155223" (miljo:"prod") fra Difi/Digipost "portal" signeringstjeneste. Host:"api.signering.posten.no". Server sertifikat: "984661185". Sertifikat eier: "SERIALNUMBER=940155223, CN=GJØVIK KOMMUNE, OU=Felles utviklingsstab, O=GJØVIK KOMMUNE, C=NO", Kø: "Default"
2019-03-12 09:49:43.273 +01:00 [Error] Feil ved henting av status fra difi portal sign
Digipost.Signature.Api.Client.Core.Exceptions.UnexpectedResponseException: ErrorType:SERVER, ErrorCode: GENERAL_ERROR, ErrorMessage: 
   at Digipost.Signature.Api.Client.Portal.PortalClient.<GetStatusChange>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)

**Comment by asjafjell** [comment]
Heisann! 

Det er forståelig at du begynner å tenke på køer her, men det er nok ikke det som skjer her. Vi har for ikke så lenge siden lagt et DoS-filter helt ytterst på vår tjeneste for å forhindre at avsendere spammer API-et vårt. Her vil du ikke få noe informasjon om neste tillatte pollingtid ettersom det før vi gjør noe prosessering. Se [dokumentasjonen vår om hastighet](https://signering-docs.readthedocs.io/en/latest/opprette-oppdrag.html#hastighet) for mer informasjon:

**Comment by talisker77** [comment]
Takk for tilbakemelding, og det er forståelig at en prøver å forhindre spamming av API. 
Mitt konkrete problem er fortsatt der, hvor vi har (på vegne av kunden) sendt i oppdrag på pollingqueuename = null og vi klarer ikke å få tak i disse oppdragene når vi poller på tjenesten
1) direkte = queuename=direkte-guid
2) portal = queuename=portal-guid
3) direkte =queuename=null
4) portal=queuename=null
Skulle gjerne ha fått tak i de oppragene som er laget mot queuename = null, slik at vi kan stenge ned polling mot denne køen. 

Det kan nok også være korrekt at den versjonen kunden benytter seg av nå er litt vel aktiv og treffer denne problemstillingen slik at vi ikke får ta i oppdragene. 

Er det noe vi kan få gjort for å få ta i oppdragene?

Så skal vi jobbe mot kunden for å oppgradert etterhvert.

**Comment by asjafjell** [comment]
Er det en spesiell grunn til at du ønsker å sende inn `PollingQueue=null` og ikke bare la være å spesifisere den? Om du sender inn en forespørsel med en `Sender` uten `PollingQueue` satt så vil den få `PollingQueue.Default`. Det kan du også bruke ved uthenting.

**Comment by Git07Omkar** [comment]
Hei !

Kan du sende meg link til code/api dokumentasjon som viser hvordan vi kan trigge varsel.

Har sjekket den nye link for dokumentasjon men har ikke funnet det jeg leter etter.

Trenger eksempel kode på hvordan vi kan trigge send ekstra varsel.
![DigipostUpdate](https://user-images.githubusercontent.com/48719127/54606065-c2698a80-4a70-11e9-8210-5da561d1559c.png)

Med vennlig hilsen

**Comment by talisker77** [comment]
PollingQueuename = null blir gjort for å trigge Deault kø, og slik er det gjort, men det er egentlig bare en detalj i problemet. Ser at TooEager trigges på OrgNr og ikke kø, slik at en kan få et scenario som dette:
direkte = queuename=direkte-guid
portal = queuename=portal-guid
direkte =queuename=null
portal=queuename=null => TooEagerPollingException

og hvis samme rekkefølge gjentar seg, så får en ikke ned ventende oppdrag fra Default portal kø.
Og selv om en da har flere køer, kan en risikere å aldri klare å hente ned oppdrag fra noen køer, hvis en virksomhet har flere (les:3parts løsninger som bruker signering med samme virksomhetsertifikat, men forskjellig kø).

Slik situasjonen er nå, så får en p.t. ikke lastet ned oppdrag som er opprettet på default kø, på grunn av dette.

**Comment by asjafjell** [comment]
@Git07Omkar: vi har ikke endepunkt for å kunne gjøre dette. Det kan kun gjøres fra web.

**Comment by Git07Omkar** [comment]
Takk for ditt svar.
Jeg vil ha dette på nettet, og hvis du vil gi meg prøvekode i .net som er kjørbar i webapplikasjonen, så vil det være veldig hjelpsomt for meg.

**Comment by runeflobakk** [comment]
@talisker77: 
Vi skiller ikke på _type integrasjon_ (direkte, portal) når vi avgjør om man har lov til å spørre etter status. Dette løses ved å spesifisere separate kønavn for hver integrasjon slik at man spør på separate køer, slik jeg tolker det som dere nå har implementert for hhv. deres direkte- og portal-integrasjon.

Slik jeg forstår dette så forsøker dere å tømme køene med navn `null` fordi dere har gått over til å spesifisere ulike kønavn for direkte- og portal-integrasjonene deres. Det er bra! Slik jeg forstår det så ønsker dere å "tømme køene" for direkte- og portal-integrasjonene deres med `polling-queue=null`, for så å avvikle polling på disse køene. Stemmer dette?

Jeg foreslår følgende: har dere mulighet til å stenge ned f.eks. direkte-integrasjonen, og la portal-integrasjonen få gjøre seg ferdig med å hente oppdrag på `null`-køen. Når den er ferdig, slutter dere å spørre mot `null`-køen for portaloppdrag, og starter direkte-integrasjonen igjen og lar den tømme sin `null`-kø på tilsvarende måte.

**Comment by asjafjell** [comment]
@Git07Omkar: Kan du opprette et nytt issue? Det du lurer på er helt urelatert til denne tråden. Jeg sletter dine kommentarer her og oppfordrer til å lage et nytt issue så skal vi hjelpe deg så godt vi kan.

**Comment by talisker77** [comment]
@runeflobakk: Din oppsummering av problemstillingen er rett. 
Jeg prøver å tømme køen =NULL, men da får jeg bare feil i klienten/dotnet
2019-03-21 18:18:23.735 +01:00 [Debug] Henter status for Tenant: "Gjøvik"(Id:1), org: "940155223" 
2019-03-21 18:18:24.015 +01:00 [Error] Feil ved henting av status fra difi portal sign
Digipost.Signature.Api.Client.Core.Exceptions.UnexpectedResponseException: ErrorType:SERVER, ErrorCode: GENERAL_ERROR, ErrorMessage: 
   at Digipost.Signature.Api.Client.Portal.PortalClient.<GetStatusChange>d__3.MoveNext()

**Comment by runeflobakk** [comment]
Bare så jeg 100% sikker på at jeg skjønner omfanget her. Den stacktracen du gjengir i siste melding, er den i.f.m. at dere får `TooEagerPollingException`, eller er den urelatert til det? Får dere den feilen selv om dere poller på `null`-køen fra bare _én_ integrasjon om gangen, altså stopper pollingen fullstendig i f.eks. direktesignatur-integrasjonen, og kun poller i portal-integrasjonen? (som jeg foreslår i forrige svar)

**Comment by talisker77** [comment]
TooEagerPollingException og UnexpectedResponseException er nok urelatert. UnexpectedResponseException virker som om den kommer når en pollet på Default kø. Det kan virke som om oppdrag i Default (NULL) kø ikke har vært fullstendig nedlastet. Etter en grundig gjennomgang, fant vi oppdragene, hvor de var bekreftet mottatt, men PADES/XADES var ikke lastet ned. Dette blir bare gjetting, da feilen ikke er særlig beskrivende. 

TooEagerPollingException er noe uklar når den slår til. 
Er denne pr. kø, pr orgnr eller pr sertifikat?

Løsningen som er implementert er multi tenant og skiller ikke mellom direkte og portal, slik at det ikke er mulig å slå av direkte og/eller portal hver for seg. Vi poller bare sekvensielt. 
Løsning poller direkte, så portal eller portal så direkte. Vi prøver å få til slik at siste poll ikke får neste poll slot. 

Hadde vi hatt bedre oversikt over status for de forskjellige køer/kunder/systemer, så hadde nok vi klart å beskrive problemet bedre ved starten. 

Feilen **"Digipost.Signature.Api.Client.Core.Exceptions.UnexpectedResponseException: ErrorType:SERVER, ErrorCode: GENERAL_ERROR, ErrorMessage:
at Digipost.Signature.Api.Client.Portal.PortalClient.d__3.MoveNext()"**
ga inntrykk av at noen var feil ved henting av oppdrag status/endringer, men i overgangen til bruk av navngitte køer ble ikke gamle oppdrag flyttet korrekt, slik at fullførelse av nedhenting av oppdrag ikke skjedde korrekt. 

Oppdragene for jobb id'er (1386826, 1386302) er nå hentet ned. 
Usikker om det finnes flere oppdrag i Default(NULL) kø for nevnte org.

Hvis den er tom, så kan vi nok avslutte denne. 
Hadde det vært mulig å tatt dette pr. telefon, kunne det nok gitt et raskere og bedre utfall enn en lang issue her på git. ;)

**Comment by runeflobakk** [comment]
> Løsningen som er implementert er multi tenant og skiller ikke mellom direkte og portal, slik at det ikke er mulig å slå av direkte og/eller portal hver for seg. Vi poller bare sekvensielt.

`TooEagerPollingException` (altså `429 TOO MANY REQUESTS`-respons fra server) skjer i to distinkte tilfeller:
- per virksomhetssertifikat, dersom en integrasjon gjør mer enn 10 requests per sekund. Dette er globalt for hele tjenesten. (generelt DoS-filter)
- spesifikk backoff-policy som enforces i polling-endepunkt(er). Dersom et poll-respons indikerer intet resultat/ingen endringer eller tilsvarende må man vente før man forsøker å polle igjen. For signeringstjenesten enforces dette _per kø + per avsender-orgnr_. I dette tilfellet vil responsen inneholde headeren `X-Next-permitted-poll-time` som angir tidligste tidspunkt man får lov til å gjøre ny poll-request. Dersom dette ikke overholdes vil dette tidspunktet bare forskyves fremover.

Dersom dere får `TooEagerPollingException` så skjer altså en av de to overnevnte, og man kan skille på de ved å se om exception-en inneholder `NextPermittedPollTime`. 

_Egentlig_, når man får respons som indikerer tom kø skal man inspisere `NextPermittedPollTime` for å se når man kan gjøre ny poll-request. Dessverre ser jeg at .NET-klienten eksponerer ikke denne verdien fra responsen. Dette betyr i praksis, slik klientenbiblioteket er implementert p.t., at man ved tom kø må fyre av gårde en ny poll-request, få `429 TOO MANY REQUESTS`-respons tilbake som klienten gjør om til `TooEagerPollingException`, plukke ut `NextPermittedPollTime` fra exception, og deretter overholde dette tidspunktet før man forsøker å polle igjen.


> Usikker om det finnes flere oppdrag i Default(NULL) kø for nevnte org.
> Hvis den er tom, så kan vi nok avslutte denne.

Jeg har tatt en titt i databasen hos oss her, og det ser ut som dere har ett portal-oppdrag fra 7. januar i år med id `1323008` som ligger på kø `null`.

**Comment by talisker77** [comment]
> Jeg har tatt en titt i databasen hos oss her, og det ser ut som dere har ett portal-oppdrag fra 7. januar i år med id 1323008 som ligger på kø null.
Ok, da har vi flyttet den til null kø poll. Men denne skulle være utløpt for lenge siden...

> Dessverre ser jeg at .NET-klienten eksponerer ikke denne verdien fra responsen. Dette betyr i praksis, slik klientenbiblioteket er implementert p.t., at man ved tom kø må fyre av gårde en ny poll-request, få 429 TOO MANY REQUESTS-respons tilbake som klienten gjør om til TooEagerPollingException, plukke ut NextPermittedPollTime fra exception, og deretter overholde dette tidspunktet før man forsøker å polle igjen.
Da forstår jeg hvorfor vi til stadig får denne request, når en spør på tom kø.

**Comment by asjafjell** [comment]
Se gjerne release 5.1.0.0 som gjør det lettere å forholde seg til kvitteringene som kommer tilbake. Vi får nå `Next permitted poll time` på kvitteringene, noe som gjør at det feltet bør brukes for å bygge opp polling-flyt. Vi skal få lagt ut eksempler på hvordan det _bør_ gjøres i løpet av ganske kort tid.
