### ISSUE TITLE
Digipost Document sending for signature with message 

### ISSUE THREAD

**Issue by Git07Omkar** [digipost/signature-api-client-dotnet#190]
Hi !

Can you send me a link to code / api documentation showing how we can trigger notification.

Have checked the new documentation link but haven't found what I'm looking for.

Need example code on how we can trigger send extra notice.
![DigipostAPIEnhancementImg](https://user-images.githubusercontent.com/48719127/55154932-0d278880-517c-11e9-862b-d5ac3e5dcfc7.png)

**Comment by asjafjell** [comment]
Hi, I am sorry to say that it is not possible to do this via the API at the moment. We will take this into consideration when creating new features.

**Comment by Git07Omkar** [comment]
When you expect it will be ready to implement in  Dot Net.

**Comment by asjafjell** [comment]
There is unfortunately no plans of implementing this feature. There may be some downsides by making this available via the API, which must be explored.
