### ISSUE TITLE
Birthday does not seem to show when signing with BankID on mobile

### ISSUE THREAD

**Issue by amundaa** [digipost/signature-api-client-dotnet#192]
# Birthday not showing in signature when signing with mobile Bank ID

When using only e-mail as ContactInformation and signing with mobile Bank ID, the birthday of the signer does not seem to show on the signed document. When signing with "normal" Bank ID however, it seems to work fine.

The job is created just fine and is giving no errors. We are making sure that the appopriate property is set:
`
job.IdentifierInSignedDocuments = Digipost.Signature.Api.Client.Core.Enums.IdentifierInSignedDocuments.DateOfBirthAndName;
`
Is this a natural limitation from using mobile Bank ID, or is it a bug?

Br,
Amund

**Comment by asjafjell** [comment]
Hi!

I am sorry to inform you that this is a limitiation. I am happy to immediately inform you that we know that this can now be solved. We are looking into this now, and hope to fix it within reasonable time.

**Comment by ogetz** [comment]
Hi, 

Could you please provide an updated status on this issue? Any estimate on when we can expect that this issue is resolved? We have a customer waiting impatiently for this fix. 

Regards, 

Ove

**Comment by asjafjell** [comment]
Hi again. 

We have not been able to fully investigate this issue, but I will discuss with my team today and see if we can get this fixed ASAP. You will hear from me shortly. 

Thank you for your patience.

**Comment by asjafjell** [comment]
We are unfortunately not able to fix this issue right now. We are, at the moment, unsure of when this will be fixed, but it is one of our next tasks to be picked up. Sorry that i cannot give you an exact time of fix.

**Comment by ogetz** [comment]
Do you have any idea about the timeframe (weeks, months)? We are considering implementing full social security number as a workaround (not optimal, as the SSN will be visible for all who are to sign), but we need to know if the same issue will hit us also there? Will SSN be visible in the signature for documents signed with bankID on mobile?

**Comment by ogetz** [comment]
Hi, 

Please respond to my follow up question above, as we need to communicate to our customer what the alternatives are. 

Regards, 

Ove

**Comment by asjafjell** [comment]
Hi! Just to be sure, I would expect it to be months, not weeks. We are unable to give you a date, as we are unsure when it can be done.

**Comment by ogetz** [comment]
Hi!
Thanks for your response to one of my two questions. 

The other question is whether the same limitation is also present if we implement the full social security number, which is a third option (next to "name only" and "name and birthday")? 

Ove

**Comment by asjafjell** [comment]
Hi again! Sorry for not answering both of your questions. Unfortunately, this is a limitation with Bank ID on mobile, and will therefore not work with SSN. We are ready to fix this as soon as we are able to, but we are experiencing some technical limitations at the moment. We will let you know as soon as we release a fix.

**Comment by asjafjell** [comment]
I am happy to inform you that signing with BankID on mobile will include birth date on signed documents as of now.  It has taken more time than what we initially expected because of BankID limitations, but this is now fixed. Please do not hesitate opening another issue if you experience other issues. Closing the issue.
