### ISSUE TITLE
Eldre versjon - PortalClient.GetStatusChange() "dør". 

### ISSUE THREAD

**Issue by Trondelond** [digipost/signature-api-client-dotnet#194]
Hei, ble henvist hit fra Sture Føre, vi har et litt underlig problem.

I noen dager har vår tjeneste (benytter digipost-signature-api-client v3.0.1) pollet avgårde med en feil i sertifikat. Sertifikat er nå korrigert, men vi ser at PortalClient.GetStatusChange() rett og slett kjører og forsvinner i løse luften for oss.

Dette er en tjeneste som kjører for flere organisasjoner, og alle andre ser ut til å fungere ok. Så jeg lurer på om man kan oppleve å bli stoppet i døra på et vis for et gitt organisasjonsnummer etter for mange feilforespørsler, eller om det er noen andre tips til feilsøking her.
Tidligere fikk vi melding tilbake om at TLS ikke kunne opprettes, men nå skjer det som nevnt "ingenting" når metoden kalles for denne organisasjonen.

Sertifkat er tilsynelatende OK, med "Digital Signature" i Key Usage.

Jeg ser digipost/signature-api-specification#39 foreslås her på github, og jeg anser det ikke som usannsynlig at det fremdeles er noe galt med sertifikat, men i og med at jeg ikke får noen melding tilbake velger jeg å legge inn et issue her.

Mvh
Trond

**Comment by asjafjell** [comment]
Heisann! 

Her ble det mange tanker rundt mye forskjellig, så for meg er det ikke helt klart hva som er problemet. For å strukturere litt så spør jeg om litt ting og kommer med tanker som kan være relevant.

1. Versjonen dere bruker er 2 år gammel. Det vil også avhengigheter være. Kanskje er det avhengigheter som ikke er så stabile lenger. 
2. Hvilke feil er det dere får når kallene _ rett og slett kjører og forsvinner i løse luften for oss_?
3. I henhold til [dokumentasjonen](https://signering-docs.readthedocs.io/en/latest/opprette-oppdrag.html#hastighet) så blir man blokkert om man gjør mer enn 10 requester i sekundet per avsender. Godt mulig at det er her dere blir stoppet.
4. Fungerer det av og til eller fungerer det ikke i det hele tatt? Om det har fungert før og ikke har gått ut på dato så skal det fortsatt fungere. 

Hvis du kan svare på disse spørsmålene så blir det lettere. Skal vi svare på tekniske spørsmål så må vi nesten ha feilmeldinger for å finne ut av det.

Vi høres.

**Comment by Trondelond** [comment]
Hei, 

Mye momenter som skal ut på en gang, beklager.

1. Vi har denne funksjonaliteten i en WS som fungerer knirkefritt for alle andre foretak, det er kun dette ene der det ser ut til at det er "noe" galt med sertifikatet.
2. Vi kaller på formen : 

jobStatusChanged = await portalClient.GetStatusChange();

Og dette fungerer som nevnt fint for samtlige foretak. Men i tilfellet med dette ene foretaket får vi et nullobjekt tilbake så langt jeg kan se. 
3. Dette er nok ikke tilfellet hos oss, vi har opplevd det tidligere, men da fått _noe_ tilbake i form av feilmelding.
4. Som nevnt, dette fungerer for alle andre foretak, bortsett fra dette ene som har fått nytt sertifikat. Når det har vært gjort sertifikatbytter tidligere har man for eksempel ikke merket dette som exportable, rettigheter har ikke vært gitt, og dette har gitt oss en feilmelding tilbake. Men i dette tilfellet kommer det da et nullobjekt i retur ser det ut til.

**Comment by Trondelond** [comment]
Hei,

Har prøvd å kjøre direkte på url : https://api.signering.posten.no/api/[orgnr]/portal/signature-jobs/[jobid]/pades

for å se om vi når gjennom, og ser da at vi får : 

```
HTTP ERROR 429
Problem accessing /api/[orgnr]/portal/signature-jobs/[jobid]/pades. Reason:

    Too Many Requests
```

Vi har ikke hatt noen særlige operasjoner her siste døgnet, så hvor lenge må man vente før det åpnes for trafikk igjen? I tillegg - kan dette forårsake at klienten returnerer et nullobjekt?

**Comment by asjafjell** [comment]
Det er begrenset per organisasjonsnummer til 10 stk pr. sekund. Om dere får den meldingen uten en NextPermittedPollTime så er det denne dere treffer på. Da må dere finne ut hvilke applikasjoner som kjører og gjør kall samtidig og sørge for at de samlet holder seg under 10 i sekunder, som nevnt i dokumentasjonen jeg linket til over.

**Comment by asjafjell** [comment]
Og for å svare på på det, så blokkeres dere i ca et minutt om jeg ikke husker feil. Hvilket organisasjonsnummer gjelder dette?

**Comment by Trondelond** [comment]
Hei, takk for svar! Nå har vi slått av sendingen i noen døgn for organisasjonen, da er det i så fall ukjente tjenester for oss som går mot dere. Dette kan kanskje du se?

Orgnr : 883974832

Hvis det er så at det er snakk om et minutts blokkering så er det noe mystisk i alle fall, da vi har sett denne meldingen i et par dager, sannsynligvis lenger.

**Comment by PetterSa** [comment]
Hei @Trondelond , vi ser at det kommer en del REST requests med URL `/api//portal/signature-jobs` hvor det ikke er lagt til organisasjonsnummer i urlen. De kommer fra IP `91.186.72.47` som ser ut som det kan være relatert til dere. 
Vi kan dessverre ikke sjekke om orgnr på disse requestene tilhører dere ettersom vi ikke logger dette utover at det står i urlen. Disse kommer i såpass høy frekvens at de utløser DOS-filteret vårt, som blokkerer basert på organisasjonsnummeret i sertifikatet. Dette betyr at alle requester dere gjør med dette orgnummeret vil bli blokkert.

Kan dere sjekke opp i om dette virker kjent?

**Comment by Trondelond** [comment]
Hei @PetterSa, jeg skal ta en avsjekk internt her hos oss. 

Forstår jeg deg riktig at det kommer en bråte requests til dere på formen du nevner uten orgnr, men det presenteres med orgnummeret 883974832 i sertifikatet?
Kan du si noe om hyppigheten?

**Comment by kjetilsbl** [comment]
@Trondelond Det kommer rundt 30 requests i sekundet på den ugyldige urlen `/api//portal/signature-jobs` fra IP `91.186.72.47`. Disse blir blokkert av DOS-filteret vårt og blir møtt med responskode `429 - Too many requests`. Applikasjonen som gjør disse spørringene har ikke implementert en fornuftig backoff-rutine: istedenfor å bremse spørringene når den mottar responskode 429 prøver den tilsynelatende umiddelbart på nytt, noe som holder applikasjonen i en kontinuerlig tilstand av blokkert. IPen som blir brukt er mistenkelig lik `91.186.72.51` som av og til gjør kall på den _gyldige_ urlen `/api/883974832/portal/signature-job`, som jo inneholder deres orgnr. Vi mistenker derfor at den spammende applikasjonen tilhører dere.

DOS-filteret vårt ser på sertifikatet på hver spørring mot tjenesten vår. Dersom samme sertifikat (verifisert på orgnr) blir brukt mer enn 10 ganger i sekundet blir alle requests med dette sertifikatet blokkert. Dette er uavhengig av hvor kallene kommer fra rent IP-messig. Dersom det stemmer at den spammende applikasjonen bruker et sertifikat med orgnr `883974832` vil altså alle spørringer som gjøres med dette sertifikatet bli blokkert.

Får dere fikset dette? Forstår det som at dere jobber under et visst tidspress mtp på noen kontrakter som må ut litt kvikt, og vi ønsker å bistå dere så godt vi kan for å få dem ut i tide😊

**Comment by Trondelond** [comment]
@kjetilsbl Vi er i full sving med å prøve å finne hva den `91.186.72.47` maskinen er hos oss.

Du nevner at 

> av og til gjør kall på den gyldige urlen

For å dobbeltsjekke : betyr dette at det også kommer feilaktige kall fra` 91.186.72.51 `?

**Comment by Trondelond** [comment]
Oppfølgingsspørsmål : Kommer disse 30 requestene i sekundet kontinuerlig, eller er det irregulært?

**Comment by kjetilsbl** [comment]
Kallene fra `91.186.72.51` ser fornuftige ut, ingen ugyldige urler i hvert fall. Noen få kall til /api/883974832/portal/signature-jobs/<OPPDRAGS_ID>/pades` slipper igjennom, men blir besvart med `403 - Forbidden`. Kan virke som det prøves å hente ut en pades dere ikke har tilgang til.

De 30 spørringene i sekundet har vært kontinuerlig hele uken ja.

**Comment by Trondelond** [comment]
Ok, det er da enda godt å høre. Da er det fornuft i det som kommer fra der vi forventer det. Vi jobber fremdeles med å finne `91.186.72.47` her hos oss.

**Comment by kjetilsbl** [comment]
Den er god, hold oss gjerne oppdatert og spør hvis dere lurer på noe mer😊

**Comment by Trondelond** [comment]
IP-adressene var uvurderlige i feilsøkingen, det viser seg at det var en ny tjeneste som ikke var ferdig konfigurert som hadde løpt løpsk. Så feilsøkingen på applikasjonen som rapporterte feilen var bare symptomet på et problem andre steder. 
Nå flyter dokumentene igjen, tusen takk for hjelpen!

**Comment by asjafjell** [comment]
Supert at det ordnet seg. Lukker denne.
