### ISSUE TITLE
Signering og .NET Framework

### ISSUE THREAD

**Issue by hdsoftware** [digipost/signature-api-client-dotnet#231]
Vårt system er basert på .NET Framework og jeg finner ingen god måte å bruke dette biblioteket på, med mindre jeg lager et rammeverk for utveksling av data mellom CORE og Framework.  Jeg tok kontakt med vår mann Fredrik Bach hos dere og han videreformidlet dette til Rune Svendsen og han hevder at PORTAL og CLIENT biblioteken finnes for Framework.
Jeg har lett og lett til øyet blir stort og vått, men finner altså ingenting.  Veldig fint om dere kan henvise meg til riktig NUGET pakke.

**Comment by asjafjell** [comment]
Heisann! Vi gikk over til .NET Core for omtrent ett år siden. Releasene for .NET Framework er fortsatt tilgjengelige, men vi har skjult disse fordi vi ønsker at kundene skal ta seg bryet med å oppgradere til .NET Core 2.1, siden vi ikke oppgraderer med ny funksjonalitet der. .NET 3.0 ble nylig lansert, så kravet om 2.1 er ganske lavt. 

Vi har ikke mulighet for å nyutvikle på mange plattformer samtidig, så den nyeste funksjonaliteten vil ikke være tilgjengelig i .NET Framework-versjonen. Den gamle klienten finner du info om [på Nuget](https://www.nuget.org/packages/digipost-signature-api-client/). Dokumentasjonen vår har ikke endret seg mye for kodeeksempler, men kan avvike litt på sertifikathåndtering og logging. Håper dette hjelper deg litt på vei.

**Comment by asjafjell** [comment]
Det er altså versjon `4.4.0` som er .NET Framework-versjonen. Det glapp fra forrige post.

**Comment by hdsoftware** [comment]
Litt usikker på hva dette har med at 2.0 er lavere enn 3.0 å gjøre.  Vi er på .NET Framework og har ingen planer om å gå over til hverken Standard eller CORE.
Vi får gjøre en vurdering og se om vi går for Digipost signerings løsningen eller ikke. Litt usikker, med tanke på at dere ikek vedlikeholder Framework versjonen lenger.  All forståelse av at dere ønsker ett kodesett å forholde dere til.

Mvh ole..

Fra: Aleksander Sjåfjell <notifications@github.com>
Sendt: fredag 4. oktober 2019 12:29
Til: digipost/signature-api-client-dotnet <signature-api-client-dotnet@noreply.github.com>
Kopi: Ole Morten Heien <omheien@advisor.no>; Author <author@noreply.github.com>
Emne: Re: [digipost/signature-api-client-dotnet] Signering og .NET Framework (#231)


Heisann! Vi gikk over til .NET Core for omtrent ett år siden. Releasene for .NET Framework er fortsatt tilgjengelige, men vi har skjult disse fordi vi ønsker at kundene skal ta seg bryet med å oppgradere til .NET Core 2.1, siden vi ikke oppgraderer med ny funksjonalitet der. .NET 3.0 ble nylig lansert, så kravet om 2.1 er ganske lavt.

Vi har ikke mulighet for å nyutvikle på mange plattformer samtidig, så den nyeste funksjonaliteten vil ikke være tilgjengelig i .NET Framework-versjonen. Den gamle klienten finner du info om på Nuget<https://www.nuget.org/packages/digipost-signature-api-client/>. Dokumentasjonen vår har ikke endret seg mye for kodeeksempler, men kan avvike litt på sertifikathåndtering og logging. Håper dette hjelper deg litt på vei.

**Comment by hdsoftware** [comment]
ok

Mvh ole..

Fra: Aleksander Sjåfjell <notifications@github.com>
Sendt: fredag 4. oktober 2019 12:32
Til: digipost/signature-api-client-dotnet <signature-api-client-dotnet@noreply.github.com>
Kopi: Ole Morten Heien <omheien@advisor.no>; Author <author@noreply.github.com>
Emne: Re: [digipost/signature-api-client-dotnet] Signering og .NET Framework (#231)


Det er altså versjon 4.4.0 som er .NET Framework-versjonen. Det glapp fra forrige post.

**Comment by asjafjell** [comment]
.NET Core 2 ble lansert i 2017 og det er allerede rukket å bli 2 år siden.  Vi krever ikke at dere går over til noe som ble nettopp lansert, men noe som har vært i markedet en god stund. Det er en avgjørelse vi har ventet lenge med, men nå måtte vi gjøre det for å få opp utviklingstakten. Det var ikke et resultat av at vi hadde bugs vi ikke klarte løse. 4.4.0 er en stabil versjon og de aller fleste avsenderne bruker den. 

Jeg anbefaler deg å sjekke [versjonsloggen på Github fra 4.4.0](https://github.com/digipost/signature-api-client-dotnet/releases) og frem til i dag for å se hva som er gjort. Som du ser så er det svært få kritiske endringer og bare 1 funksjonell endring knyttet til engangslenker som er lagt til.

Om dere integrerer med oss på .NET Framework-versjon, så vil det være en smal sak å oppgradere til .NET Core i fremtiden når dere er klare. Det er i hovedsak nytt pakkenavn, ellers er det meste identisk.

Håper dette gir deg nok informasjon til å gjøre en vurdering.

**Comment by hdsoftware** [comment]
Ok.  Jeg må innrømme at jeg aldri har testet ut CORE annet enn at jeg prøvde meg på signerings biblioteket deres så jeg vet jo ikke hvor gjennomsiktig det er mot FrameWork.  Kanskje kan jeg bare bytte fra FrameWork til Core på prosjektene og rekompilere, kanskje ikke, men jeg mistenker det vil skape problemer med tanke på at vi bruker flere tredje parts komponenter som er skrevet for Framework

Uansett så skal jeg ta opp dette på neste utviklermøte, som er til mandag, så får vi se hva som kommer ut av dette..

Mvh ole..

Fra: Aleksander Sjåfjell <notifications@github.com>
Sendt: fredag 4. oktober 2019 14:38
Til: digipost/signature-api-client-dotnet <signature-api-client-dotnet@noreply.github.com>
Kopi: Ole Morten Heien <omheien@advisor.no>; Author <author@noreply.github.com>
Emne: Re: [digipost/signature-api-client-dotnet] Signering og .NET Framework (#231)


.NET Core 2 ble lansert i 2017 og det er allerede rukket å bli 2 år siden. Vi krever ikke at dere går over til noe som ble nettopp lansert, men noe som har vært i markedet en god stund. Det er en avgjørelse vi har ventet lenge med, men nå måtte vi gjøre det for å få opp utviklingstakten. Det var ikke et resultat av at vi hadde bugs vi ikke klarte løse. 4.4.0 er en stabil versjon og de aller fleste avsenderne bruker den.

Jeg anbefaler deg å sjekke versjonsloggen på Github fra 4.4.0<https://github.com/digipost/signature-api-client-dotnet/releases> og frem til i dag for å se hva som er gjort. Som du ser så er det svært få kritiske endringer og bare 1 funksjonell endring knyttet til engangslenker som er lagt til.

Om dere integrerer med oss på .NET Framework-versjon, så vil det være en smal sak å oppgradere til .NET Core i fremtiden når dere er klare. Det er i hovedsak nytt pakkenavn, ellers er det meste identisk.

Håper dette gir deg nok informasjon til å gjøre en vurdering.

**Comment by asjafjell** [comment]
Om du ikke har testet ut Core, så kan du jo bare teste klient med versjon 4.4.0 og så ev. oppgradere når du har fått testet.

**Comment by hdsoftware** [comment]
Yess.  Skal gjør det.  Kan være vi finner ut at vi kaster oss over CORE sentralt i stedet.  Vi får se…

Mvh ole..

Fra: Aleksander Sjåfjell <notifications@github.com>
Sendt: mandag 7. oktober 2019 12:22
Til: digipost/signature-api-client-dotnet <signature-api-client-dotnet@noreply.github.com>
Kopi: Ole Morten Heien <omheien@advisor.no>; Author <author@noreply.github.com>
Emne: Re: [digipost/signature-api-client-dotnet] Signering og .NET Framework (#231)


Om du ikke har testet ut Core, så kan du jo bare teste klient med versjon 4.4.0 og så ev. oppgradere når du har fått testet.

**Comment by simenstoa** [comment]
Hei, @hdsoftware! Nå har vi oppdatert klienten så den også skal støtte .Net Framework <= 4.6.1 (https://github.com/digipost/signature-api-client-dotnet/releases/tag/7.0.0). Anser problemet som løst, men lag gjerne et nytt issue om det ikke fungerer som forventet.
