### ISSUE TITLE
When using the Portal client(.Net Core), cannot create a job  with a signer having defined as ContactInformation

### ISSUE THREAD

**Issue by VioFlu** [digipost/signature-api-client-dotnet#239]
Hello,

I am working on a "Document signing" integration using your apis and I need to identify the signer by Email address.

I used the code samples available in the documentation to test, when having as a signer Identifier "ContactInformation" object I get the following error:ErrorCode: CONTACT_INFORMATION_BY_LOOKUP_IS_REQUIRED, ErrorMessage: Providing contact information is not permitted. Contact information must be retrieved by lookup.

If I remove ContactInformation signers, I get this Error: ErrorType:CLIENT, ErrorCode: CONTACT_INFORMATION_BY_LOOKUP_IS_REQUIRED, ErrorMessage: Providing contact information is not permitted. Contact information must be retrieved by lookup.
Code:
            var signers = new List<Signer>
            {
                new Signer(new PersonalIdentificationNumber("00000000000"), new NotificationsUsingLookup()),
                new Signer(new PersonalIdentificationNumber("11111111111"), new Notifications(
                    new Email("myVioEmail@mail.com"),
                    new Sms("VioNo")))
            };

You have a note in the documentation about that:
_You may identify the signature job’s signers by personal identification number IdentifiedByPersonalIdentificationNumber or contact information. **When identifying by contact information**, you may choose between instantiating a PortalSigner using IdentifiedByEmail, IdentifiedByMobileNumber or IdentifiedByEmailAndMobileNumber._

But no  C# example,  I didn't find anything in the API code to help me figure out how to use PortalSigner.

Can you please help me with some code samples?

**Comment by PetterSa** [comment]
For public services using lookup is mandatory. The only instance in which this is not mandatory is if the signer is signing on behalf of someone else (like a company), in which case you have to set the OnBehalfOf flag.
