### ISSUE TITLE
Question about job's CancellationReference.Url

### ISSUE THREAD

**Issue by VioFlu** [digipost/signature-api-client-dotnet#249]
Hi again :),

I have noticed that for the test environment you have the following Url "template" for the cancelling opperation:  https://api.difitest.signering.posten.no/api/**OrganizationNumber**/portal/signature-jobs/**JobId**/cancel

Is it possible(safe) instead of saving the CancellationReference.Url, to replace the known variables(OrganizationNumber & JobId) in the Uri. And what will be the end point in production?

Thanks,

**Comment by asjafjell** [comment]
Hi!

Is there any reason for not persisting the URL itself? We will guarantee that the operation will work at all times. If you do URL manipulation, this guarantee disappears. 

For the same reason, we have configured the URLs for all environments in the class `Environment`, so that users of the library does not have to deal with URL manipulation.

**Comment by VioFlu** [comment]
Hi,

Thank you for your answer, 
The reason is that we don't want to extend our model which is also used for another signing provider and cause confusion for the future development. However we'll think how to introduce this in our model to not be confusing for the other signing solutions,

**Comment by asjafjell** [comment]
It is understandable that you do not want to change your data model, but pulling out the "important bits" from the URL undermines the purpose of our REST API, and will certainly cause confusion for future developers if we choose to alter this URL later on. I would invest time in how you can properly manage signature jobs from both providers without hacks to ensure a future proof solution. All hacks with URLs are  at your own risk.

**Comment by VioFlu** [comment]
I understand, thank you for your answer :)
