### ISSUE TITLE
Error when signing documents where signers are identified by a customidentifier

### ISSUE THREAD

**Issue by JonasADBovuet** [digipost/signature-api-client-dotnet#250]
When we create a signing job (using direct flow) where the signer is identified by a custom identifier, we get the following error message during the sign in process, straight after logging in using bank id: "En feil oppstod under signeringen. Hvis du ønsker, kan du prøve igjen." (shown at the url: https://preprod.signicat.com/std/docaction/difi/responsive/abs/?performedAction=authbased&methodName=idporten-abs-niva4-nossn-sign). When using personal identification number as signer identifier, this issue does not arise.

We use version 4.4.0 of the client library for .NET Framework, and the signature job is created in the following way:

``` c#
var clientConfiguration = new ClientConfiguration(Environment.DifiTest, /*Certificate*/, new Sender(/*orgnummer*/));

var directClient = new DirectClient(clientConfiguration);

var documentToSign = new Document(
    "Subject of Message",
    "This is the content",
    FileType.Pdf,
    @"C:\Path\ToDocument\File.pdf");

var exitUrls = new ExitUrls(
    new Uri("http://redirectUrl.no/onCompletion"),
    new Uri("http://redirectUrl.no/onCancellation"),
    new Uri("http://redirectUrl.no/onError")
    );

var signers = new List<Signer>
{
    new Signer(new CustomIdentifier("custom_identifier"))
};

var job = new Job(documentToSign, signers, "reference_to_signature_job", exitUrls);

var directJobResponse = await directClient.Create(job);
```

According to Difi, it should be possible to create signature jobs where the signer is identified by a custom identifier, but I can't find any examples on how this is done in the documentation. Hence I wonder if I have created the signing job in a correct manner?

**Comment by asjafjell** [comment]
Heisann, @JonasADBovuet, og takk for sist! 🏇

Først vil jeg bare beklage for at vi svarer så sent. For å kunne sjekke denne opp så trenger vi litt mer informasjon.

- Hvorfor bruker dere ikke nyeste versjon av biblioteket? Det er blitt luket ut en del feil siden i fjor høst, så vi anbefaler absolutt å oppgradere.
- Kunne du gjort en ny request til f.eks. Difitest og gitt oss tidspunktet den ble gjort, slik at vi kan sjekke loggene våre? 😊

**Comment by JonasADBovuet** [comment]
Heisann, takk for sist ja 😄.

Applikasjonen kjører på .NET Framework og det er derfor gammel versjon er tatt i bruk. Hvis dette kan være kilden til problemet skal jeg undersøke hvorvidt det er plausibelt å oppgradere til .NET Core innenfor de rammene vi har.

Jeg kjørte en forespørsel nå mot Difi-test. Signeringsoppdraget ble opprettet 17. desember ca kl. 12:48:59. Signeringsoppdraget ble signert (les: logget inn med bank id) ca kl. 12:50:58. Da ble jeg sendt til feilside referert i første innlegg.

**Comment by kjetilsbl** [comment]
Skjønner! Var vanskelig å skille ut hvilke requester som er interessante i loggene tross de veldige spesifikke tidspunktene, har du mulighet til å oppgi et orgnummer, eller gjengi urlen på kallet som feiler?😊 Kunne du også bekreftet at det faktisk er difitest dere kjører mot, og ikke feks difiqa?

**Comment by JonasADBovuet** [comment]
Hei, jeg har sjekket i kode og kan bekrefte at det er Difi-test vi kjører mot. Signeringslenken som ble tatt i bruk var som følger: https://difitest.signering.posten.no/signere/#/-/oyY94ezkGcdFp5_Gr0iIMsRBQk_ZKzu7AI1lGLeSbD8

**Comment by kjetilsbl** [comment]
Takk! Hmm dette var merkelig. Vi kan ikke se at det har skjedd noe galt i loggene våre, men venter på svar fra underleverandør om feilen kan ha oppstått der. Gir beskjed så fort vi får svar😊

**Comment by asjafjell** [comment]
Det viser seg at feilen oppstår under signering fordi dere ikke bruker en testbruker som er registrert i InfoTorg. Her må altså en testbruker fra BankID brukes. Siden dere tester med en offentlig konto, så er det vel Difi som kan gi dere det om dere ikke har det allerede.

**Comment by JonasADBovuet** [comment]
Tusen takk for løsning! Da skal jeg ta kontakt med Difi for å få tilgang til en testbruker som er registrert i InfoTorg.

**Comment by JonasADBovuet** [comment]
Jeg fikk nå tilsendt testbrukere fra Difi som er registrert i InfoTorg. Jeg signerte et oppdrag med signatar identifisert med egendefinert identifikator og signeringen ble gjennomført som den skulle. Jeg lukker derfor denne saken. Tusen takk for god hjelp!
