### ISSUE TITLE
Klientbiblioteket må kunne støtte Logging av request og respons 

### ISSUE THREAD

**Issue by aberner** [digipost/signature-api-client-dotnet#27]
Klientbibliotekene må selvsagt støtte at en Avsender/databehandler har behov for å logge requester og responser generert og sendt fra klientbiblioteket.
Dette er viktig i feilsøking og er ofte etterspurt i feilsituasjoner.

Som regel ber Posten at klienten oppgir dette og at alle klienter har kontroll på og forståelse for hva de sender fra seg.

Det er forventet at klientbiblioteket støtter dette på en enkel og dokumentert måte. F.eks. slik det er gjort her: https://github.com/difi/sikker-digital-post-klient-java

**Comment by asjafjell** [comment]
Vet ikke hvorfor denne har sneket seg under radaren, men det er notert, og blir sett på så snart som mulig.

**Comment by asjafjell** [comment]
Dette er fikset i [1.0.5920.28098-beta3](https://www.nuget.org/packages/digipost-signature-api-client/1.0.5920.28098-beta3)
