### ISSUE TITLE
Oppdrag status via API

### ISSUE THREAD

**Issue by talisker77** [digipost/signature-api-client-dotnet#300]
Vi har tilgang til å laste ned pades og xades via dagens api. 
Hvis det nå skulle skje at vi ikke klarte så laste ned dokumentene og må laste ned pades og xades i etterkant. Vi har tilgang på pades Id, men mangler da xades Id. 

Finnes det en mulighet å få tak i xades id for oppdraget når vi kun har pades id?

**Comment by simenstoa** [comment]
Hei, url for å laste ned både PAdES og XAdES skal være tilgjengelig når du henter status for jobben: https://signering-docs.readthedocs.io/en/latest/client-integration/direct-flow.html#step-4-get-signed-documents. Håper det hjelper.

**Comment by talisker77** [comment]
Her er det ønske om å hente status på oppdrag med tilhørende xades id, etter at en har hentet status. 
Altså oppdraget er signert, en har da ikke tatt vare på xades id, men har mistet oppdraget (data-krasj, osv..) og ønsker å gjenopprette data. Da er spørsmålet:

Finnes det en mulighet å få tak i xades id for oppdraget når vi kun har pades id?

**Comment by simenstoa** [comment]
Okey, usikker på om jeg skjønner dette helt, så gjerne forklar casen deres nærmere om jeg svarer på noe annet. 

En PAdES id gir bare mulighet til å hente ut en PAdES, men hvis dere har tatt vare på [statusQueryToken](https://signering-docs.readthedocs.io/en/latest/client-integration/direct-flow.html#status-by-token), er det mulig å hente status på nytt. Og der kan dere finne url til både PAdES og XAdES.

Forøvrig inneholder en PAdES også alle XAdESer, så den er et fullverdig bevis i seg selv.

**Comment by simenstoa** [comment]
Hei, er det noe mer jeg kan hjelpe med? Eller kan jeg lukke issuet?

**Comment by talisker77** [comment]
Detter gjelder portalsigneringer og vi tidligere tok ikke vare på pades og xades url etter oppdraget var hentet ned. Casen her gjelde da, å kunne hente ned filene i etterkant, hvis noe (uforutsett) har skjedd slik at filene er mistet. 
Dere skriver at dette ikke er mulig. Da kan dere bare lukke. 

Takk

**Comment by simenstoa** [comment]
Skjønner. Litt usikker på hvordan dere hentet ut PAdES id, men om dere har den er det mulig å hente ut PAdES basert på den. Hvis id ikke inneholder `--j` kan du bruke [arkiv-klienten](https://signering-docs.readthedocs.io/en/latest/client-integration/archive-client.html). Hvis ikke kan dere gjenskape URL basert på hvordan URL-er dere lagrer for PAdES ser ut nå. Merk at om dere ikke har [langtidsvalidering](https://signering-docs.readthedocs.io/en/latest/lagring.html#langtidsvalidering-og-lagring) skrudd på er den uansett bare tilgjengelig i 40 dager.
