### ISSUE TITLE
eSignering feilmelding i test

### ISSUE THREAD

**Issue by andreasle** [digipost/signature-api-client-dotnet#301]
Ved oppretting av signeringsjobb får jeg en feilmelding tilbake: «Det oppsto 鮠eller flere feil. ---> Digipost.Signature.Api.Client.Core.Exceptions.UnexpectedResponseException: ErrorType:SERVER, ErrorCode: UNEXPECTED_SERVER_ERROR, ErrorMessage: An unexpected error occured, and the server was not able to handle it. The error instance has been assigned the ID '3FE14DB34FB11DFA'»
 
Kan dere undersøke hvorfor denne feiler?
 
Stacktrace:
 
2020-08-18 11:20:44,071 [ERROR] [eDocument.DifiSignering.SignClient] Failed to create signature job:Det oppsto 鮠eller flere feil.
System.AggregateException: Det oppsto 鮠eller flere feil. ---> Digipost.Signature.Api.Client.Core.Exceptions.UnexpectedResponseException: ErrorType:SERVER, ErrorCode: UNEXPECTED_SERVER_ERROR, ErrorMessage: An unexpected error occured, and the server was not able to handle it. The error instance has been assigned the ID '3FE14DB34FB11DFA'
   ved Digipost.Signature.Api.Client.Core.Internal.RequestHelper.<Create>d__4`1.MoveNext()
--- Slutt p堳takksporing fra forrige plassering der unntak ble iverksatt ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   ved Digipost.Signature.Api.Client.Direct.DirectClient.<Create>d__3.MoveNext()
   --- Slutten p堳poringen av intern unntaksstakk ---
   ved System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   ved eDocument.DifiSignering.SignClient.CreateSignatureJob(HttpRequestMessage request, String docTitle, String docMessage, Byte[] pdf, String completionUrl, String rejectionUrl, String errorUrl, List`1 signers)
---> (indre unntak nummer 0) Digipost.Signature.Api.Client.Core.Exceptions.UnexpectedResponseException: ErrorType:SERVER, ErrorCode: UNEXPECTED_SERVER_ERROR, ErrorMessage: An unexpected error occured, and the server was not able to handle it. The error instance has been assigned the ID '3FE14DB34FB11DFA'
   ved Digipost.Signature.Api.Client.Core.Internal.RequestHelper.<Create>d__4`1.MoveNext()
--- Slutt p堳takksporing fra forrige plassering der unntak ble iverksatt ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   ved Digipost.Signature.Api.Client.Direct.DirectClient.<Create>d__3.MoveNext()<---

**Comment by andreasle** [comment]
Får fortsatt denne, har dere sett på feilen?

**Comment by simenstoa** [comment]
Hei, og beklager sent svar! Det kan se ut som `rejectionUrl` ikke har blitt satt når du forsøker å opprette oppdraget. Kan du sjekke at det er gjort slik som beskrevet her: https://signering-docs.readthedocs.io/en/latest/client-integration/direct-flow.html#step-1-create-signature-job

**Comment by andreasle** [comment]
Hei,
Takk for svar.
Jeg ser i koden at rejectionURL blir satt i koden vår for objektet som sendes inn for å opprette signeringsoppdrag. Har du andre tips?

[cid:image001.png@01D6850F.F74646F0]

Mvh Andreas

Fra: Simen Støa <notifications@github.com>
Sendt: mandag 7. september 2020 09.28
Til: digipost/signature-api-client-dotnet <signature-api-client-dotnet@noreply.github.com>
Kopi: Andreas Leite <Andreas.Leite@prokom.no>; Author <author@noreply.github.com>
Emne: Re: [digipost/signature-api-client-dotnet] eSignering feilmelding i test (#301)


Hei, og beklager sent svar! Det kan se ut som rejectionUrl ikke har blitt satt når du forsøker å opprette oppdraget. Kan du sjekke at det er gjort slik som beskrevet her: https://signering-docs.readthedocs.io/en/latest/client-integration/direct-flow.html#step-1-create-signature-job

**Comment by simenstoa** [comment]
> [cid:image001.png@01D6850F.F74646F0]

Ser ikke ut som bildet ble lastet opp. Har du mulighet til å helle kopiere inn koden?

**Comment by andreasle** [comment]
Hei, det ser ut som rejectionUrl var feilformatert fra vår side. Takk for hjelpen, saken er løst
