### ISSUE TITLE
Support for Multiple documents for a single Job

### ISSUE THREAD

**Issue by frno10** [digipost/signature-api-client-dotnet#302]
Hi, is it possible to add multiple documents for a single signing Job in portal flow ?

**Comment by simenstoa** [comment]
Hi, this is not possible at the moment, but is something we hope to support in the not too distant future.

**Comment by simenstoa** [comment]
Hi! We have now added support for multiple documents for a signature job in both portal and direct flow. You can test it out with the newest client (currently `8.0.0-RC1`). Let us know if there are any problems.
