### ISSUE TITLE
UnexpectedResponseException: ErrorType:SERVER

### ISSUE THREAD

**Issue by andreasle** [digipost/signature-api-client-dotnet#343]
Hei,
Vi får en UnexpectedResponseException ved kall til `await portalClient.GetStatusChange();` i produksjonsmiljø hos kunde med orgnummer 921627009. Tenker at det usannsynlig at det er en `TooEagerPollingException `siden det går et kall hver andre time? Kan dere se årsaken til feilen?

Stacktrace:
> Digipost.Signature.Api.Client.Core.Exceptions.UnexpectedResponseException: ErrorType:SERVER, ErrorCode: GENERAL_ERROR, ErrorMessage: 
>    at Digipost.Signature.Api.Client.Portal.PortalClient.<GetStatusChange>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at eDocument.Integration.DifiSignering.SignPoller.<GetStatuses>d__4.MoveNext() in C:\code\edocument\eDocument.Integration\DifiSignering\SignPoller.cs:line 69

**Comment by simenstoa** [comment]
Hei! Ser ut som dere fikk `500`-feil fordi vi ikke håndterte så godt at dere gjorde to kall samtidig på `await portalClient.GetStatusChange();`. Men kan også se at dere nå har spesifisert en kø, og at dere sluttet å få `500` etter det? 

Ser derimot at det nå kommer noen `429`-responser også, som kan tyde på at det fortsatt skjer kall for ofte. Har dere f.eks flere instanser av applikasjonen kjørende samtidig som begge spør etter status på den samme køen?

**Comment by andreasle** [comment]
Takk, det viste seg som du antydet at flere instanser av applikasjoner kjørte samtidig. Det er løst med spesifisering av køer.
