### ISSUE TITLE
Spørsmål om bruk av virksomhetssertifikat

### ISSUE THREAD

**Issue by catokolas** [digipost/signature-api-client-dotnet#351]
Kan vi som offentlig universitet i norge unngå å måtte gi fra oss vårt virksomhetssertifikat til privat tredjepart som leverer en webløsning som vil tilby digital signatur vha digipost sin signatur-api?

https://signering-docs.readthedocs.io/en/latest/egen-integrasjon/sikkerhet.html beskriver hvordan virksomhetssertifikat brukes til å identifisere seg, samt sikre konfidensialitet og meldingsintegritet vha to-veis TLS. 
Kan privat tredjepart bruke sitt eget virksomhetssertifikat og på annen måte identifisere oss (universitetet) som bruker av apiet?
Vi har allerede etablert eSignering i DigDir samarbeidsportalen.

Av it-sikkerhetsmessige årsaker ønsker vi (universitetet) ikke gi fra oss vårt virksomhetssertifikat til private tredjeparter.

**Comment by catokolas** [comment]
hei, er det noen som har noe svar/synspunkter på dette?

**Comment by simenstoa** [comment]
Hei! 

Beklager sent svar. Tredjepart kan settes opp som behandler for dere, da kan de sende inn på oppdrag på vegne av dere med sitt eget virksomhetssertifikat. De må da oppgi deres organisasjonsnummer når de spesifiser avsender av oppdraget. Dere kan kontakte DigDir for å få satt opp behandler.

Mvh Simen

**Comment by catokolas** [comment]
takk for svar - ja, jeg har vært i kontakt med DigDir og fått anbefalt Autorisasjon (https://samarbeid.digdir.no/esignering/kostnadsmodell-esignering/103), men vi har en dansk privat tredjepart firma som ikke kan bruke sitt virksomhetssertifikat i løsningen. Usikker på hva den tekniske årsaken er til det. Er det dansk organisasjonnummer som er problemet?

De ønsker heller ikke å bli et norsk registrert utenlandsk foretak (NUF), så da har vi endt opp med at de lager en separat løsning (som snakker med signatur-apiet) som vi da hoster hos oss selv.

**Comment by simenstoa** [comment]
Bare hyggelig! Ja, vi støtter bare norske virksomhetssertifikat, så da er det nok løsningen å hoste det selv.

**Comment by catokolas** [comment]
ok, lukker saken:
ps: det hadde vært nyttig hvis dokumentasjonen gjenspeilet det.
