### ISSUE TITLE
Tittel i signert dokument

### ISSUE THREAD

**Issue by oysteinthoensisjord** [digipost/signature-api-client-dotnet#353]
Jeg har oppretta en signeringsjobb hvor tittelen på jobben er satt til "Signering av erklæring", men når jeg har signert får forsiden på dokumentet tittelen "Job title". Ved oppretelse av signeringsjob blir dokumentets tittelen blir også satt og denne dukker opp som den skal i signeringssermonien

![image](https://user-images.githubusercontent.com/62872615/139022131-1b72642b-51a2-4cab-9912-a47cfed8b6f5.png)

![image](https://user-images.githubusercontent.com/62872615/139022075-87f5afe3-dc4a-49a8-bd58-400ca23509cb.png)

Hva kan være årsaken til dette?

**Comment by oysteinthoensisjord** [comment]
Er det noen som har noe forslag?

**Comment by simenstoa** [comment]
Hei! 

Beklager sent svar, og takk for at du melder det inn. Feilen lå hos oss, og ble nok innført når vi la til støtte for oppdrag med flere dokumenter i versjon 8.0. Har sluppet versjon [8.2.0](https://github.com/digipost/signature-api-client-dotnet/releases/tag/8.2.0) hvor feilen skal være rettet. Gi oss gjerne tilbakemelding hvis det fortsatt skjer i versjon 8.2.0 også.

Mvh Simen

**Comment by oysteinthoensisjord** [comment]
Takk for svar og fiks. Da har eg testa og det ser ut til å fungere fint nå. 

Helsing Øystein
