### ISSUE TITLE
FEATURE_NOT_AVAILABLE ved nedlasting av Xades på signeringsjobber med flere dokumenter

### ISSUE THREAD

**Issue by oysteinthoensisjord** [digipost/signature-api-client-dotnet#356]
Vi henter ned Xades-en etter signering for å fiske ut navnet på vedkommende som faktisk har signert. Dersom signeringsjobben inneholder flere dokument får eg feilmeldinga 
`ErrorType:CLIENT, ErrorCode: FEATURE_NOT_AVAILABLE, ErrorMessage: Get signer's XAdES for jobs with multiple documents is not available.`
![image](https://user-images.githubusercontent.com/62872615/143401547-ae6983a6-eb26-4a96-b9de-c5a4fd8f3b40.png)

Eg anntar at det muligens er gode grunner til at det nettop er slik, men er likevel undrande.

**Comment by simenstoa** [comment]
Hei! Hovedgrunnen til at vi ikke støtter dette for signeringsjobber med flere dokumenter er fordi vi da har en XAdES per dokument per undertegner. Så endepunktet for å hente ut èn XAdES for en undertegner gir ikke mening lenger. Er det bare navnet på undertegner dere henter ut?

**Comment by oysteinthoensisjord** [comment]
Aha.. Tenkte at det var noko i den rettning. Ja, det er bare navnet me henter ut.

**Comment by simenstoa** [comment]
Skjønner. Vi har dessverre ingen planer akkurat nå om å legge til støtte for å hente XAdES for signeringsjobber med flere dokumenter, men skal ta med behovet deres for å vite navnet på den som faktisk har skrevet under til teamet. Håper det ikke er en showstopper for dere for å ta i bruk signeringsjobber med flere dokumenter.

**Comment by oysteinthoensisjord** [comment]
Vi må bare klare oss uten navnet enn så lenge og håper at dere finner på noe lurt her.
