### ISSUE TITLE
Update vulnerable packages

### ISSUE THREAD

**Issue by andrewgeorgesands** [digipost/signature-api-client-dotnet#365]
Hi,

Would it be possible to release a new version with updated nuget packages?  Currently the version 5 packages from microsoft contain known vulnerabilities.  

Regards,

Andrew

**Comment by simenstoa** [comment]
Hi, 

Thanks for the heads up. The packages are updated, and a new version is released https://github.com/digipost/signature-api-client-dotnet/releases/tag/9.0.0.

- Simen

**Comment by andrewgeorgesands** [comment]
Thank you (takker og bukker) :)

Andrew
