### ISSUE TITLE
Log4net dependency

### ISSUE THREAD

**Issue by kristianenge** [digipost/signature-api-client-dotnet#44]
Fra @sukchr:
Hei, jeg ser at API-et har en dependency mot log4net, spesifikt versjon 2.0.4. Det er et ønske fra min side at logging-rammeverk abstraheres, slik at man unngår koblingen til en spesifikk versjon av log4net. Det blir fort krøll når ulike API-er har avhengigheter mot ulike versjoner av log4net..

Har dere mulighet til å vurdere bruk av Common.Logging, eller et annet API for abstraksjon av logg-rammeverk?

**Comment by kristianenge** [comment]
Hei @sukchr 

Vi har valgt å bruke log4net for vår egen skyld, siden det er dette vi er vant til. Vi har tidligere diskutert at vi burde ha en eller annen abstraksjon istedenfor og Common.logging ser ut til å være det beste alternativet. Siden dere ønsker akkurat dette mener jeg det er på god tid at vi gjør det. Ref-er deg her når en ny versjon er klar.

**Comment by sukchr** [comment]
Supert, takk!

**Comment by asjafjell** [comment]
Da er dette lagt til i [1.0.5954.22921-beta3](https://www.nuget.org/packages/digipost-signature-api-client/1.0.5954.22921-beta3). Vi har gjort intern testing og det ser ut til at det fungerer fint. Det hadde  vært fint om dere også gjorde det før vi prodsetter det, @sukchr. Takk!

**Comment by kristianenge** [comment]
Utvidet også [dokumentasjonen](http://digipost.github.io/signature-api-client-dotnet/v1.0/#Logging) med et avsnitt om hvordan man kan implementere Log4Net mot Common.Logging API-et.

**Comment by sukchr** [comment]
Takk! Jeg skal teste, kommer med tilbakemelding.

**Comment by sukchr** [comment]
Bekrefter at det fungerer fint (log4net 1.2.10)!

```
2016-04-26 21:23:18,164 [DEBUG] [Digipost.Signature.Api.Client.Direct.DirectClient] {log4net:HostName=IGCV0D5E001} Successfully created Direct Job with JobId: 236.
```

**Comment by asjafjell** [comment]
Så bra! Kjekt å se at Common.Logging fungerer!
