### ISSUE TITLE
"Skjulte" dependencies

### ISSUE THREAD

**Issue by sukchr** [digipost/signature-api-client-dotnet#47]
Jeg har en kommentar til måten nuget-pakken "digipost-signature-api-client" referer til avhengigheter.

Pakken oppgir å ikke ha noen referanser - https://www.nuget.org/packages/digipost-signature-api-client/1.0.5954.22921-beta3. Når jeg ser i selve pakken ser jeg imidlertid at blant annet Common.Logging og Newtonsoft.Json ligger "bundlet" med i pakken. 

Det kan se ut som om nuspec for "digipost-signature-api-client" bruker `<files>` istedenfor `<dependencies>`? 

Det er ønskelig fra min side at `<dependencies>` brukes. Problemet med `<files>` er at "digipost-signature-api-client" flytter pekerne til DLL-filene i csproj-filen. I tillegg blir ikke packages.config oppdatert med riktige avhengigheter. Eksempel:

Peker til Common.Logging før installasjon av "digipost-signature-api-client":
```
<Reference Include="Common.Logging, Version=3.1.0.0, Culture=neutral, PublicKeyToken=af08829b84f0328e, processorArchitecture=MSIL">
    <HintPath>..\packages\Common.Logging.3.1.0\lib\net40\Common.Logging.dll</HintPath>
```

Peker til Common.Logging etter installasjon av "digipost-signature-api-client":
```
<Reference Include="Common.Logging, Version=3.3.1.0, Culture=neutral, PublicKeyToken=af08829b84f0328e, processorArchitecture=MSIL">
    <HintPath>..\packages\digipost-signature-api-client.1.0.5954.22921-beta3\lib\net45\Common.Logging.dll</HintPath>
```

Min packages.config peker fortsatt til gammel versjon av Common.Logging etter installasjon av "digipost-signature-api-client":
``` 
<package id="Common.Logging" version="3.1.0" targetFramework="net40" />
```

**Comment by asjafjell** [comment]
Her har du et godt poeng. Vi har lagt merke til dette selv, uten å tenke så mye mer på det. Dette skal undersøkes og fikses. Takk for innspill!

**Comment by asjafjell** [comment]
Denne er nå fikset i en rykende fersk oppdatering, nemlig [1.1.5974.27948](https://www.nuget.org/packages/digipost-signature-api-client/1.1.5974.27948). Rop ut om du skulle oppleve noen problemer, @sukchr.

**Comment by sukchr** [comment]
Supert, takk!

**Comment by sukchr** [comment]
Testet, det ser flott ut! Ved update ble Common.Logging og Common.Logging.Core fjernet fra .csproj, men jeg mistenker at det er nuget som krøller det til. Nuspec-en ser fin ut :)

**Comment by asjafjell** [comment]
Flott! Takk for at du påpekte dette. Nå er det fikset på alle bibliotekene vi forvalter.
