### ISSUE TITLE
Eksempel på sertifikatvalidering for .NET?

### ISSUE THREAD

**Issue by sukchr** [digipost/signature-api-client-dotnet#50]
Hei!

Fra https://github.com/digipost/signature-api-specification#to-veis-tls:

> Det du manuelt må gjøre er å validere at sertifikatet tilhører Posten Norge AS, ved å sjekke organisasjonsnummeret som står i Common Name.

> Et godt tips er å benytte eller hente inspirasjon fra Difi sin sertifikatvalidator, som er tilgjengelig på GitHub.

Har dere tips til hvor jeg kan se for et .NET eksempel på sertifikatvalidering?

**Comment by asjafjell** [comment]
Heisann!  Dette trenger du ikke å forholde deg til, for dette blir sjekket av .NET-klienten. 

Ved respons vil det bli gjort et callback til en validator som sjekker at sertifikatet er gyldig, blant annet at organisasjonsnummeret står i _Common Name_. Hvis det er ugylidg vil selve tasken kanselleres og det vil kastes en `TaskCanceledException`.

**Comment by sukchr** [comment]
Supert, takk!
