### ISSUE TITLE
Må DirectJob ha Signer?

### ISSUE THREAD

**Issue by sukchr** [digipost/signature-api-client-dotnet#51]
Hei, spørsmål til dette kallet:

```
var directJob = new DirectJob(
	document: documentToSign,
	signer: new Signer(personalIdentificationNumber: "12345612345"),
	reference: "...",
	exitUrls: exitUrls
	);
```

Hva gjør jeg hvis fødselsnummeret på brukeren som skal signere er ukjent?

Scenarioet mitt er at en sluttbruker har startet utfylling av et skjema som han/hun selv skal signere. 

Hvis `signer` er en obligatorisk parameter i API-et, betyr det i praksis at jeg må kreve pålogging med ID-porten for å starte utfylling av skjema. 

Kunne `signer` vært optional i API-et og heller angitt av sluttbruker i signeringsdialogen (slik som for BankID)?

**Comment by SindreNordbo** [comment]
Hei, takk for et godt innspill!

Per i dag er dette feltet obligatorisk, så inntil videre må signatars fødselsnummer komme fra avsender.
Jeg skal ta dette videre og undersøke om det er noe vi kan vurdere å endre på.

**Comment by sukchr** [comment]
Takk!

**Comment by aberner** [comment]
@sukchr kan du utdype noe mer behovet her. Dette vil da være snakk om at innbygger signerer på et dokument som er auto-generert av virksomheten og at dokumentet kun inneholder opplysninger som innbygger selv har oppgitt i søknadsprosessen. 
Er dette faktisk et behov som etter loven krever avansert elektronisk signatur som skal arkiveres og valideres over lang tid? 
eller vil en elektronisk signatur være godt nok?
en elektronisk signatur basert på en ID-porten autentisering er vel det som er mest vanlig på innsendingstjenester pr. dag. Dette er kanskje en tjeneste som har spesielle lovkrav knyttet til signatur?

Det hadde vært fint med noe mer kontekst for å forstå behovet.

**Comment by asjafjell** [comment]
Om ikke @sukchr kan beskrive et eksempel der dette er nyttig,  så tenker  jeg  at vi lukker denne.

**Comment by aberner** [comment]
@asjafjell følges opp med møte i dag med @sukchr følger opp saken igjen etter det møte.

**Comment by aberner** [comment]
Da er det avtalt at denne saken lukkes og at den eventuelt følges opp dersom behovet blir konkret.

**Comment by aberner** [comment]
@asjafjell ser at jeg ikke har rettigheter til å lukke saker. men det er ihvertfall avtalt med @sukchr at saken lukkes.
