### ISSUE TITLE
Feil i frister for signering - portalsignering

### ISSUE THREAD

**Issue by torangel** [digipost/signature-api-client-dotnet#53]
Har satt følgende availability på signeringsjobben
![image](https://cloud.githubusercontent.com/assets/1355125/14953322/ecee5500-1068-11e6-81b4-adc07875bd57.png)
Og får first 01.06.2016. Mulig jeg regner feil, men jeg har satt 24 timer som availability på signeringsrequesten (60 x 60 x24 = 86400) og dette ser ut til å være gjenspeilet i avaliableseconds på availabilityobjektet.

![image](https://cloud.githubusercontent.com/assets/1355125/14953324/f4144e70-1068-11e6-9148-b0833fe302b4.png)

**Comment by asjafjell** [comment]
Hei! Det virker som jeg forstår problemet, men kan du lage et eksempel som viser akkurat det du gjør og som kompilerer. Dette gjør det lettere å gjenskape problemet ditt. Takk!

**Comment by asjafjell** [comment]
For å kunne teste denne så må vi ha et kompilerende kodeeksempel som illusterer problemet. Har du dette, @torangel? Tenker da spesifikt på den biten der du masserer tidspunkt og setter dette på oppdraget. Om det var tvetydigheter i API som førte til misforståelser så vil vi veldig gjerne vite om det.

**Comment by torangel** [comment]
Vel - Kodeeksempelet er i praksis bare at jeg lager en jobrequest og setter et nytt availability objekt med avaliablefor=24 timer på jobben. Dette resulterer i at fristen blir satt 1 mnd frem i tid i stedet for 24 timer.

```c#
var availability = new Availability();
portalJob.Availability = availability;
availability.Activation = portalSignData.TilgjengeligFra;
availability.AvailableFor = TimeSpan.FromHours(24);
```

![image](https://cloud.githubusercontent.com/assets/1355125/15245960/00741854-190a-11e6-92d0-38b4cdae1d2c.png)

**Comment by asjafjell** [comment]
Takk! Vi skal ta en kikk på dette så snart det lar seg gjøre, sannsynligvis mandag morgen.

**Comment by asjafjell** [comment]
Vi har funnet feilen, og det er så enkelt som at `Availability` aldri ble serialisert slik som den skulle. Dette førte til en tom node som igjen førte til at du fikk standardverdien som er én måned fram i tid. En fiks kommer snarlig.

**Comment by asjafjell** [comment]
Dette er nå fikset i [1.1.5983.18368-beta](https://www.nuget.org/packages/digipost-signature-api-client/1.1.5983.18368-beta). Test ut og kom gjerne med tilbakemelding.

**Comment by asjafjell** [comment]
Jeg antar denne nå er fikset. Lukkes.
