### ISSUE TITLE
Mulig å angi foretrukket språk?

### ISSUE THREAD

**Issue by sukchr** [digipost/signature-api-client-dotnet#54]
Hei, er det mulig å angi eksempelvis engelsk/bokmål/nynorsk ved opprettelse av `DirectJob`?

**Comment by asjafjell** [comment]
Hei! Når du sier språk, mener du språk i portalen for Posten signering, eller tenker du på noe annet?

**Comment by sukchr** [comment]
Jeg mener språk i portalen for Posten signering. Altså språket som sluttbrukeren ser i grensesnittet.

**Comment by lillesand** [comment]
Det er dessverre ikke støttet per nå. Det skal være støtte for at sluttbrukeren selv kan velge språk i inne i løsningen, men det ser ut som den har falt bort nå. Jeg har lagd en oppgave på få den inn igjen.

Jeg er enig i at vi bør ha funksjonalitet for at tjenesteeierportalen bør kunne angi forhåndsvalgt språk gjennom APIet. Jeg legger inn en oppgave på det, men kan dessverre ikke love noe om når den blir prioritert.

**Comment by asjafjell** [comment]
Jeg lukker denne saken siden det ikke er noe mer utestående. Vi kan åpne den igjen om det skulle bli mer diskusjon rundt dette.

**Comment by sukchr** [comment]
Helt i orden, takk for tilbakemelding!
