### ISSUE TITLE
Dokumentasjon for parameter "fileName"

### ISSUE THREAD

**Issue by sukchr** [digipost/signature-api-client-dotnet#56]
Hei, to spørsmål knyttet til "fileName" parameteren til i Document-konstruktøren:

1. hva brukes den til? Når jeg klikker på "Vis dokument" i signeringsportalen blir filnavnet "435.pdf", "436.pdf", osv. 
2. hvilke karakterer er godkjent i fileName?

Altså:
```
var documentToSign = new Document(
		...
		fileName: "...",
		...
```

Jeg har fått et par tilfeller av UnexpectedResponseException når filnavnet tydeligvis inneholder karakterer som ikke er godkjent (i dette tilfellet krøllparenteser):
```
[UnexpectedResponseException: ErrorType:CLIENT, ErrorCode: ASICE_VALIDATION_FAILED, ErrorMessage: Error when valicating ASiCE: Parse error: Failed to find hash for: [%7Bform%7D-GAVFUI.pdf]]
   Digipost.Signature.Api.Client.Core.<Create>d__4`1.MoveNext() +1136
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   Digipost.Signature.Api.Client.Direct.<Create>d__2.MoveNext() +554
```

**Comment by asjafjell** [comment]
Dette er et felt som blir brukt til å navngi filen i selve ASiC-E-pakken, og har ikke noe å si for sluttbruker. Dette parameteret vil forsvinne. Det raske svaret er derfor at du kan sette det til hva som helst som ikke er spesialtegn.

**Comment by sukchr** [comment]
Takk!
