### ISSUE TITLE
Ønskelig at DirectJobResponse er [Serializable]

### ISSUE THREAD

**Issue by sukchr** [digipost/signature-api-client-dotnet#57]
Hei, av dokumentasjonen (http://digipost.github.io/signature-api-client-dotnet/v1.0-1.1/) har jeg forstått det slik at jeg må ta vare på DirectJobResponse før jeg videresender bruker til signeringsportalen, slik at jeg kan sjekke status på signeringsjobben når brukeren blir redirected tilbake. For meg er det da naturlig å legge DirectJobResponse i session.

```
var directJobResponse = await directClient.Create(directJob);
Session["directJobResponse"] = directJobResponse;
RedirectToUrl(directJobResponse.ResponseUrls.Redirect.Url.ToString());
```

Det er ønskelig at `DirectJobResponse` er dekorert med `[Serializable]`-attributet slik at andre session-moduser enn InProc kan benyttes (e.g. StateServer/SQLServer).

Når jeg benytter StateServer-mode får jeg følgende ved forsøk på å legge DirectJobResponse i session:

>  Unable to serialize the session state. In 'StateServer' and 'SQLServer' mode, ASP.NET will serialize the session state objects, and as a result non-serializable objects or MarshalByRef objects are not permitted. The same restriction applies if similar serialization is done by the custom session state store in 'Custom' mode.

> [SerializationException: Type 'Digipost.Signature.Api.Client.Direct.DirectJobResponse' in Assembly 'Digipost.Signature.Api.Client.Direct, Version=1.1.5974.27948, Culture=neutral, PublicKeyToken=683b8efceae684a6' is not marked as serializable.]

**Comment by asjafjell** [comment]
Jeg ser hva du ønsker å gjøre og #52 løser dette så snart den blir lukket. Klientbiblioteket kommer ikke til å få klasser merket med `[Serializable]`, men den pullrequesten vil gjøre slik at du kan mellomlagre verdiene i `DirectJobResponse` og lage et nytt instans når du trenger det.

Ser på det i løpet av dagen.

**Comment by asjafjell** [comment]
Dette kan du nå gjøre hvis du bruker [1.1.5982.23427-beta](https://www.nuget.org/packages/digipost-signature-api-client/1.1.5982.23427-beta).

**Comment by sukchr** [comment]
Takk, jeg bekrefter at dette dekker behovet mitt.
