### ISSUE TITLE
GetPades() resulterer i "System.Net.WebException: The request was aborted: The request was canceled."

### ISSUE THREAD

**Issue by sukchr** [digipost/signature-api-client-dotnet#58]
GetXades() fungerer fint. GetPades() resulterer i exception. Tips til hva årsaken kan være?

> [WebException: The request was aborted: The request was canceled.]
   System.Net.ConnectStream.EndRead(IAsyncResult asyncResult) +8286373
   System.Net.Http.WebExceptionWrapperStream.EndRead(IAsyncResult asyncResult) +37

> [IOException: The read operation failed, see inner exception.]
   System.Net.Http.WebExceptionWrapperStream.EndRead(IAsyncResult asyncResult) +417534
   System.Net.Http.StreamToStreamCopy.BufferReadCallback(IAsyncResult ar) +83

> [HttpRequestException: Error while copying content to a stream.]
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   Digipost.Signature.Api.Client.Core.Internal.<GetResponseData>d__5.MoveNext() +742
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   Digipost.Signature.Api.Client.Core.Internal.<LogResponse>d__4.MoveNext() +245
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   Digipost.Signature.Api.Client.Core.Internal.<SendAsync>d__1.MoveNext() +874
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   Digipost.Signature.Api.Client.Core.Internal.<SendAsync>d__0.MoveNext() +340
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   Digipost.Signature.Api.Client.Core.Internal.<SendAsync>d__0.MoveNext() +270
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +49
   Digipost.Signature.Api.Client.Core.Internal.<SendAsync>d__1.MoveNext() +528
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +49
   Digipost.Signature.Api.Client.Core.<GetStream>d__5.MoveNext() +582
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   Digipost.Signature.Api.Client.Direct.<GetPades>d__6.MoveNext() +292
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +49
   Kommune247.Controllers.<HandleReturn>d__1.MoveNext() in c:\code\kommune24-7\src\Kommune24-7\Controllers\DifiSignController.cs:42
   System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state) +5103620
   System.Web.LegacyAspNetSynchronizationContext.CallCallbackPossiblyUnderLock(SendOrPostCallback callback, Object state) +82

**Comment by asjafjell** [comment]
At requesten blir `canceled` kommer som oftest av at du ikke får kontakt med _signering.posten.no_ ikke er tilgjengelig fra tjenesten din eller at innholdet ikke validerer. Her må du få tak i exception som blir kastet og sjekke hva feilmeldingen er. Jeg ser du får en `WebException`, og denne blir nok kastet av webserveren din. Hvis du graver litt inn og ser hvor den blir kastet så finner du nok raskt ut av det.

**Comment by sukchr** [comment]
Av stack-trace ovenfor kan det se ut til at den underliggende feilen er [HttpRequestException: Error while copying content to a stream.] Denne kommer så vidt jeg kan se via Digipost.Signature.Api.Client.

Jeg gjør et kall til GetStatus() rett før kallet til GetPades() returnerer feil. Det virker derfor ikke som om kontakt med serveren er problemet. Som nevnt fungerer også GetXades() utmerket. Jeg kan ikke se hvordan denne feilmeldingen blir kastet av webserveren min.

Googlet litt - https://www.google.no/search?q=HttpRequestException%3A+Error+while+copying+content+to+a+stream.&oq=HttpRequestException%3A+Error+while+copying+content+to+a+stream.&aqs=chrome..69i57j69i58.361j0j7&sourceid=chrome&ie=UTF-8#q=HttpRequestException:+Error+while+copying+content+to+a+stream

**Comment by asjafjell** [comment]
Lag et eksempel som illustrerer denne feilen og som som kan stå alene uten web. Vi trenger også loggen for å analysere dette. Takk!

**Comment by asjafjell** [comment]
Det har nå gått en uke uten å få noe mer input her. Lukker denne.
