### ISSUE TITLE
Exception: ErrorType:CLIENT, ErrorCode: ASICE_VALIDATION_FAILED, ErrorMessage: Error when valicating ASiCE: Parse error: Failed to parse XMLDirectSignatureJobManifest

### ISSUE THREAD

**Issue by sukchr** [digipost/signature-api-client-dotnet#63]
Begynte å få denne feilmeldingen i dag ved kall til `DirectClient.Create`. Mener dette fungerte for et par dager siden. Jeg går mot test-miljøet.

> ErrorType:CLIENT, ErrorCode: ASICE_VALIDATION_FAILED, ErrorMessage: Error when valicating ASiCE: Parse error: Failed to parse XMLDirectSignatureJobManifest

![image](https://cloud.githubusercontent.com/assets/157539/15571596/04043ee0-233c-11e6-8339-e5f56ca9eb54.png)

**Comment by asjafjell** [comment]
Problemet her er at miljøene for tiden er i endring fordi det kommer ny funksjonalitet. Jeg kommer tilbake til deg litt senere med hvilket miljø du bør kjøre mot og hvilken versjon av klienten.

**Comment by sukchr** [comment]
Takk, kjekt å vite at det ikke var jeg som hadde krøllet til noe :)

**Comment by asjafjell** [comment]
Hvis du kjører mot `Environment.DifiTest` og siste prodsatte versjon som ikke er beta (`1.1.5974.27948`), så skal det fungere fint.

**Comment by sukchr** [comment]
Aha, takk! Men, da mister jeg muligheten til å hente ut DirectJobResponse.JobId og DirectJobResponse.ResponseUrls..
