### ISSUE TITLE
Hva betyr de ulike JobStatusene?

### ISSUE THREAD

**Issue by sukchr** [digipost/signature-api-client-dotnet#65]
Hei, ønsker litt utdypende tekst om hva de ulike JobStatusene innebærer. 

NoChanges skjønner jeg.

Betyr CompletedeSuccessfully at alle signatarer har signert?
Betyr Failed at én eller flere signatarer har avvist signering? Eller betyr det at API kallet mot signeringsportalen feilet? 
Betyr InProgress at noen, men ikke alle, signatarer har signert? 

![image](https://cloud.githubusercontent.com/assets/157539/15963278/f50ea4a8-2f10-11e6-8f15-d75499c33d09.png)

**Comment by asjafjell** [comment]
> Betyr CompletedeSuccessfully at alle signatarer har signert?

Ja

> Betyr Failed at én eller flere signatarer har avvist signering? 
Det stemmer.

> Betyr InProgress at noen, men ikke alle, signatarer har signert?
Helt korrekt.

`InProgress` og `Failed` hadde ikke noen beskrivelse. Det har de nå, og er tilgjengelig i [1.2.6008.21155-beta](https://www.nuget.org/packages/digipost-signature-api-client/1.2.6008.21155-beta).
