### ISSUE TITLE
Spørsmål: Kombinere synkrone og asynkrone signeringsoppdrag når flere signatarerer skal signere på det samme dokumentet?

### ISSUE THREAD

**Issue by sukchr** [digipost/signature-api-client-dotnet#68]
Er det hensiktsmessig å kombinere synkrone og asynkrone signeringsoppdrag når flere signatarerer skal signere på det samme dokumentet?

Scenario: Person 1 fyller ut og sender inn et skjema som skal signeres av Person 1 og Person 2.

API-et gjør det teoretisk mulig å løse dette på to måter, men hvilken er mest riktig/hensiktsmessig?

**Løsning 1**: Person 1 signerer som en del av skjemainnsending, altså som et synkront (Direct) signeringsoppdrag. Når Person 1 har fullført signering opprettes det et asynkront (Portal) signeringsoppdrag for Person 2.

**Løsning 2**: Person 1 signerer IKKE som en del av skjemainnsending. Når person 1 har fullført innsending opprettes det asynkrone (Portal) signeringsoppdrag for Person 1 og Person 2.

**Comment by SindreNordbo** [comment]
Hei!

Dersom det er viktig at begge personer signerer på _det samme dokumentet_ (altså at det signerte dokumentet til slutt vil inneholde begges signaturer) er eneste alternativ p.t. **løsning to**, med en liten modifikasjon – det opprettes _ett_ asynkront signeringsoppdrag med to mottakere.

Ved **løsning en** vil det måtte opprettes to ulike signeringsoppdrag, og de vil dermed ikke være «koblet sammen» på noen måte. Det vil altså for eksempel ikke være mulig å hente ut signert dokument (PAdES) med begge personenes signaturer på i dette tilfellet.

Et annet alternativ til dette er under utvikling – det vil snart være mulig å opprette synkrone oppdrag med flere signatarer (på samme måte som asynkrone har i dag). Ved bruk av denne funksjonaliteten vil flyten kunne være omtrent slik:

1. Person 1 fullfører innsending
1. De opprettes ett synkront oppdrag hvor både person 1 og 2 er signatarer
1. Person 1 signerer umiddelbart i avsenders portal
1. Person 2 får varsel om å logge seg inn i avsenders portal
1. Person 2 signerer i avsenders portal

Vi er altså ikke ferdig med dette _helt_ enda, men du kan f.eks ta en titt på [denne pull-requesten i tjenestespesifikasjonen](https://github.com/digipost/signature-api-specification/pull/46) for å få en følelse av hvordan APIet vil se ut. Klientbiblioteket vil naturligvis også bli utvidet til å støtte dette.


**For å oppsummere:**

Hvis det er ønskelig at brukerne signerer i portalen til avsender: opprett synkront signeringsoppdrag med flere mottakere.
Hvis ikke: gå for **løsning to** som du skisserer.

Vi regner med å ha flersignatar på synkron signering tilgjengelig "ganske snart" :)

**Comment by sukchr** [comment]
Takk for utfyllende info!!
