### ISSUE TITLE
System.NullReferenceException at Digipost.Signature.Api.Client.Core.BaseClient.MutualTlsHandler()

### ISSUE THREAD

**Issue by sukchr** [digipost/signature-api-client-dotnet#69]
Hei, jeg får System.NullReferenceException. Stacktrace:

````
at Digipost.Signature.Api.Client.Core.BaseClient.MutualTlsHandler()
at Digipost.Signature.Api.Client.Core.BaseClient.MutualTlsClient()
at Digipost.Signature.Api.Client.Core.BaseClient..ctor(ClientConfiguration clientConfiguration)
````

Jeg benytter digipost-signature-api-client versjon 1.4.6026.24181.

Den samme koden kjører fint fra min utviklermaskin. Feilen oppstår kun i verifikasjonsmiljøet vårt.

**Comment by asjafjell** [comment]
Her trenger vi litt mer å gå på, @sukchr. Kan du gi oss hele stacktrace med linjenummer, mot hvilket miljø du går og gjerne kodesnutten du prøver å kjøre. Takk!

**Comment by sukchr** [comment]
Hei, min feil! Jeg hadde glemt å angi en del ting i opprettelse av ClientConfiguration.

Jeg kommer litt videre, men får nå en ny feil, lager egen sak på det.
