### ISSUE TITLE
TooEagerPollingException i testmiljø gjør det mer tidkrevende å utvikle og teste

### ISSUE THREAD

**Issue by ivarboms** [digipost/signature-api-client-dotnet#75]
Er det mulig å fjerne eller minske tiden man blir blokkert i testmiljø?

**Comment by SindreNordbo** [comment]
Hei, skjønner at det kan være litt plagsomt under testing!

Har justert ned grensa til 30 sekunder slik at det fortsatt er mulig å verifisere at dere håndterer denne situasjonen korrekt, men at det blir kortere tid å vente :)
