### ISSUE TITLE
Samtlige portal jobber får status FAILED

### ISSUE THREAD

**Issue by ivarboms** [digipost/signature-api-client-dotnet#76]
Jeg får opprettet jobber, og får tilbake job ID og kansellering URL.

Når jeg poller for statusendringer har samtlige jobber status FAILED. Signaturstatus er alltid RESERVED eller NOT_APPLICABLE. NOT_APPLICABLE kommer kun for fødselsnummeret 12345678910 fra eksempelet deres. MOD11 verifisering feiler for dette fødselsnummeret, vet ikke om det er relevant. Jeg har ikke testet veldig mange fødselsnummer.

Org nummer er 835302202 og job ID er f.eks. 109.

Når jeg logger inn på https://test.signering.posten.no som en person som har fått en jobb står det bare `Det er ingen dokumenter som venter på signering`.

Hva er det som går galt?

**Comment by SindreNordbo** [comment]
Hei,

grunnen til at du får `RESERVED` er fordi disse mottakerene ikke finnes eller er reservert i [Kontakt- og reservasjonsregisteret](https://digipost.github.io/signature-api-specification/v1.0/#bruk-av-kontakt--og-reservasjonsregisteret) til Difi. Signeringstjenesten gjør et oppslag der for å innhente varslingsinformasjon _når avsender er en offentlig virksomhet_. 

Private virksomheter kan derimot ikke innhente informasjon derfra, så du kan med andre ord ikke bruke `NotificationsUsingLookup` når du oppretter `Signer`en, du må bruke `Notifications` og angi e-postadressen og/eller mobilnummeret mottakeren skal bli varslet på.

Vi er i ferd med å rulle ut en ny versjon i testmiljøene som begrenser bruken av `NotificationsUsingLookup` for avsendere som ikke har anledning til å bruke Kontakt- og reserversjonsregisteret.

NB: fint om du bruker QA-miljøet vårt (`qa.signering.posten.no` – ikke `test.signering.posten.no`) som nevnt her: https://github.com/digipost/signature-api-client-dotnet/issues/74#issuecomment-247244721

**Comment by ivarboms** [comment]
Takk for svar!
