### ISSUE TITLE
Manglende støtte for signaturtype og sikkerhetsnivå ved opprettelse av signeringsoppdrag

### ISSUE THREAD

**Issue by hfriedrich** [digipost/signature-api-client-dotnet#88]
Ved opprettelse av et signeringsoppdrag finnes det ikke noe mulighet for å spesifisere signaturtypen og sikkerhetsnivå.

I følge [funksjonell dokumentasjon for Posten signering](https://digipost.github.io/signature-api-specification/v1.0/#signaturtype) skulle dette være mulig.

**Comment by SindreNordbo** [comment]
Det stemmer at denne muligheten ikke finnes i dette klientbiblioteket p.t. Vi jobber med å få ut en versjon med dette nå, og tar sikte på å ha den tilgjengelig i løpet av de nærmeste dagene.
Jeg sier fra når den nye versjonen er ute!

**Comment by SindreNordbo** [comment]
Hei igjen @hfriedrich ,

version [2.1.0](https://github.com/digipost/signature-api-client-dotnet/releases/tag/v2.1.0) er nå lansert med støtte for å spesifisere signaturtype og sikkerhetsnivå.
