### ISSUE TITLE
Mulighet for skjule deler av fødselnummer i signert dokument

### ISSUE THREAD

**Issue by amundaa** [digipost/signature-api-client-dotnet#98]
Hei,

Finnes det mulighet for å skjule personnummeret fra et fødselsnummer på padesen?
Dvs. at det på forsiden av det signerte dokumentet kun er opplyst fødselsdato med de resterende nummer skjult (123456*****).

Vi bruker .NET biblioteket for Portal-integrasjon. Har lett i dokumentasjonen, men har ikke klart å finne ut av dette.

Mvh,
Amund

**Comment by SindreNordbo** [comment]
Hei Amund,

Det finnes dessverre ingen støtte for dette i dag. Vi kommer imidlertid til å lansere muligheten for å fjerne hele fødselsnummeret fra de signerte dokumentene om ikke lenge. Jeg har ingen nøyaktig dato til deg for øyeblikket, men vi satser på å ha dette klart tidlig på høsten. Hvis dette tilfredsstiller behovet deres kan du gi en liten lyd, så skal jeg sørge for å holde deg oppdatert om dette :)

Vennlig hilsen
Sindre

**Comment by amundaa** [comment]
Hei Sindre,

Det kommer til å fungere fint for vår del. Ingen must have, bare en could have.
Flott om du gir en lyd når det er klart :)

Mvh,
Amund

**Comment by SindreNordbo** [comment]
Hei igjen, @amundaa

Denne funksjonaliteten er tilgjengelig i versjon [4.1.0](https://github.com/digipost/signature-api-client-dotnet/releases/tag/v4.1.0) som ble sluppet i dag.
