### ISSUE TITLE
Availability

### ISSUE THREAD

**Issue by amundaa** [digipost/signature-api-client-dotnet#99]
Hei,

Sikkert en dum liten sak dette, men vi får ikke helt til å sette availabiltity for en job via .NET APIet:
    
``` CSHARP
   Job job = new Job(
                    documentToSign,
                    listOfSigners,
                    vReference
                    );
                //Bare for test-formål
                TimeSpan ts = new TimeSpan(14, 0, 0, 0);

                Availability jobAvailable = new Availability();
                jobAvailable.AvailableFor = ts;

                job.Availability = jobAvailable;
                
                //Har ikke mulighet til å kjøre awaitable task
                JobResponse x = portalClient.Create(job).Result; 

```

Noe som mangler eller er feil?
Feilmeldingen vi får er en NullReferenceException. Det fungere fint om vi ikke setter AvailableFor.

Mvh,
Amund

**Comment by asjafjell** [comment]
Heisann!

Beklager et lovlig sent svar. Håper dere også har hatt litt ferieavvikling og at det ikke har stoppet helt opp. 

Takk for god problembeskrivelse. For å kunne reprodusere dette så trenger vi å vite hvilken linje som feiler. Jeg har nå testet denne kodesnutten og `jobAvailable.AvailableFor` settes fint uten problemer, men det er kanskje ikke det som feiler?

**Comment by asjafjell** [comment]
Siden vi ikke har hørt noe mer så regner vi med at denne er løst.
